### ISSUE TITLE
updateCart

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#11]
currently, checkout and addCartProduct works without providing the orderId of the cart.

on the other hand, if you want to update the order with e.g. the billig address, you have to know the orderID.

introduce a updateCart mutation to fix that

**Comment by pozylon** [comment]
Yeah lack of consistency. 

Also, the current implementation of checkout and addCartProduct needs to be redone: We have a big feature request at a customer who needs to have multiple carts per user for his requirements. I guess we could fix this while implementing the new "Multi-Cart" feature, consistently asking for the orderId to update.

**Comment by pozylon** [comment]
I will solve these requirements like this:

New cart convenience mutations:
- updateCart

Renamed (BREAKING):
- checkout to checkoutCart

New order manipulating mutations in preparation of "multi-cart":
- checkoutOrder
- addOrderProduct
- updateOrderItemQuantity
- removeOrderItem
- addOrderDiscount
- removeOrderDiscount

That way, a very simple checkout is possible without fetching the orderId once in one big query but the full feature set is only available when using the indirect methods.

**Comment by pozylon** [comment]
Done in PR #18
