### ISSUE TITLE
New Filter Type: Auto Classified Ranges

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#112]
Add New Filter Type "Classified Ranges" which allows range generation per assortment. product id's are not cached by filter but by assortment/filter combination with ad-hoc classes.
Should support a variety of configuration parameters:

- open-end
- open-start
- nominal class width

This would enable meaningful price filters for example.

Theory:
https://de.m.wikibooks.org/wiki/Statistik:_Klassierung_eines_metrischen_Merkmals_mit_vielen_verschiedenen_Ausprägungen

**Comment by pozylon** [comment]
This is crazy complex btw.

**Comment by pozylon** [comment]
![Uploading Bildschirmfoto 2020-07-22 um 12.08.16.png…]()

**Comment by pozylon** [comment]
<img width="407" alt="Bildschirmfoto 2020-07-22 um 12 08 16" src="https://user-images.githubusercontent.com/2109393/96295027-8ea86b00-0fed-11eb-81a8-8df5a9931a4e.png">

**Comment by Mikearaya** [comment]
https://www.syncfusion.com/react-ui-components/react-range-selector

**Comment by pozylon** [comment]
We got one step closer to this by introducing the RANGE filter type that simplifies the queries with RANGE filters, there's more to do here though.

**Comment by pozylon** [comment]
It was never a customer requirement, so I will close this for the moment, RANGE filter type is enough for now.
