### ISSUE TITLE
Always create a cart when there is a user

### ISSUE THREAD

**Issue by claudiocro** [unchainedshop/unchained#116]
Currently a cart for a user only gets created when there is logged in user/guest and this user adds a product into cart, else the cart is `null`. At first glance this looks ok. 

We are running into a problem with this logic. We are forced to refetch the cart after the first product has been added, we cannot use the response from updateCart to update our apollo cache, as the cart in the cache is null and after the user adds the first product to cart we will get an `_id` for this new cart. Apollo cache does not update the cart in the cache because they are different. We are forced to refetch some cart queries in order to make everything work.

A solution would be to always create a cart for the user. After the user create user, after login if the cart is null and after the user checks out cart, just recreate a new one.

**Comment by pozylon** [comment]
I see, or maybe create a cart when me.cart would return null (in the query resolver)

**Comment by schmidsi** [comment]
Isn't it an anti-pattern to alter the database on a query?
