### ISSUE TITLE
improve logging and env-vars

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#117]
the logger has a sophisticated api, but there are some problems:

- most queries and mutation log without specifying a level. This falls back to info. I think logging every query should have level:debug or verbose and therefore should not be done on production. If mutations should also be debug/verbose is debateable.
- logging without specifying a level should not be possible (typechecking ftw.)
- logging db could specify a expire index (see https://docs.mongodb.com/manual/tutorial/expire-data/)
- its only possible to pass a `debug: boolean` to the logger, which sets the logged level to either info or debug. It might be better to pass the log level as a string (and throw on unknown configs)
- (don't use the singleton pattern for the logger, its unessesary)

**Comment by pozylon** [comment]
Thanks, good stuff, I actually made something for another project which uses DEBUG env variable parsing like the famous "debug" npm package but it's actually a winston wrapper, I could enhance that logic to allow setting the log level for default logging (default is error):

```
import { createLogger, format, transports } from "winston";
import util from "util";

const { DEBUG = "" } = process.env;
const { combine, label, timestamp, colorize, printf } = format;

const debugStringContainsModule = (debugString, moduleName) => {
  const loggingMatched = debugString.split(",").reduce((accumulator, name) => {
    if (accumulator === false) return accumulator;
    const nameRegex = name
      .replace("-", "\\-?")
      .replace(":*", "\\:?*")
      .replace("*", ".*");
    const regExp = new RegExp(`^${nameRegex}$`, "m");
    if (regExp.test(moduleName)) {
      if (name.slice(0, 1) === "-") {
        // explicitly disable
        return false;
      }
      return true;
    }
    return accumulator;
  }, undefined);
  return loggingMatched || false;
};

const myFormat = printf(
  ({ level, message, label: _label, timestamp: _timestamp, ...rest }) => {
    const otherProps = JSON.parse(JSON.stringify(rest));
    const otherPropsString = Object.keys(otherProps).length
      ? util.inspect(otherProps, {
          colors: true
        })
      : "";
    return `${_timestamp} [${_label}] ${level}: ${message} ${otherPropsString}`;
  }
);

export default moduleName => {
  const loggingMatched = debugStringContainsModule(DEBUG, moduleName);
  return createLogger({
    format: combine(
      timestamp(),
      label({ label: moduleName }),
      colorize(),
      myFormat
    ),
    transports: [
      // new transports.File({
      //   level: "verbose",
      //   filename: resolveSyncCatalogLogsPath(new Date())
      // }),
      new transports.Console({ level: loggingMatched ? "debug" : "error" })
    ]
  });
};

```

**Comment by pozylon** [comment]
Also I think we should drop the current logging collection entirely and make a new event log for stuff that needs to be logged in the db like: "user adds product to cart", "user checks out cart", ...

**Comment by pozylon** [comment]
logging db could specify a expire index (see https://docs.mongodb.com/manual/tutorial/expire-data/) -> this is done in the currybag branch and will hit master later this month

**Comment by pozylon** [comment]
> most queries and mutation log without specifying a level. This falls back to info. I think logging every query should have level:debug or verbose and therefore should not be done on production. If mutations should also be debug/verbose is debateable.
There is a new env var called "LOG_LEVEL" which allows to specify the default level to log, so if you want to disable the "access log" for queries and mutations, you can adjust that to LOG_LEVEL=warn.

> logging without specifying a level should not be possible (typechecking ftw.)

Agreed, this rule could be added during typescript integration (other issue). Will not do for the moment.

> logging db could specify a expire index

Implemented


> its only possible to pass a debug: boolean to the logger, which sets the logged level to either info or debug. It might be better to pass the log level as a string (and throw on unknown configs)


The logger can now contain a pattern which is matched against the log message. Some examples follow.

log all log messages no matter what log level (even debug trace and verbose):
DEBUG=*

log all messages for loggers that start with the moduleName "unchained"
DEBUG=unchained*

> (don't use the singleton pattern for the logger, its unessesary)

The recommended way of doing logging is now:
```
import { createLogger } from 'meteor/unchained:core-logger';
const logger = createLogger('unchained:api');
logger.info(`query logs: ${limit} ${offset} ${userId}`); // eslint-disable-line
```

 With these changes in place, I think we can close this issue.
