### ISSUE TITLE
[core] Log/Record IP, remote port and user_agent_string for crucial actions

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#118]
Crucial actions:

(Everywhere where `... logFields` is used)

- [ ] order-deliveries
- [ ] order-payments
- [ ] orders
- [ ] quotations

**Comment by pozylon** [comment]
That's cool

**Comment by schmidsi** [comment]
@pozylon Touching this subject again and also in connection to #316. Why do we have `logFields` on some models and [on others, the logs are fetched from the `logs` collection](https://github.com/unchainedshop/unchained/blob/master/packages/core-users/db/helpers.js#L139)?

I'd like to streamline this. We might put all the logging functionality into the events. The question is, who reads data from the logs?

**Comment by pozylon** [comment]
I think logs should just be like timestamp + level + message + meta and could be anything, it's just what you can see on stdout and you can deactivate when you don't need to see the logs in the controlpanel.

- Events should be predefined like timestamp + EVENT_NAME + payload without arbitrary messages. If the event is PRODUCT_ADDED_TO_CART, {userId, productId, quantity.. } it can be translated by a UI like "User X added Product Y with quantity 5 to the Order Z"...
- The information in logFields is something you want to store for audit purposes like when the police knocks at your door and asks what the IP was of that user that has been paying by credit card on time/date...

So depending on how transient we will make the events, logFields could be replaced by events. An order could trigger these kind of events for ex.
ORDER_FAILED_PAYMENT (ip, user, reason...),,
ORDER_FAILED_PAYMENT (ip, user, reason...),,
ORDER_SUCCESSFUL_PAYMENT (ip, user...),

**Comment by schmidsi** [comment]
Thanks for the explanation. One thing that we need to keep in mind is the ability to access logs from the code:

For example: The order confirmation mail to the support team needs to include the IP address of the buyer. How can we access the logs and find this IP?

My suggestion is to provide an interface from the logging module. Something like:

```js

LogModule.findLogs({ type: "ADD_TO_CART_MUTATION", cartId: "asdf" });

```

**Comment by pozylon** [comment]
Mutation in the type name is propably wrong because it should be independent from the api package.

I'd strictly distinguish:
Logs -> Arbitrary messages, Untyped with Severity
Events -> Typed, Semantic, no Severity/Level

So if you need that I'd go with
```
EventModule.findEvents({ type: "PRODUCT_ADDED_TO_CART", cartId: "asdf" });
```

Or EventModule.on("PRODUCT_ADDED_TO_CART", (userId, context) => Users.update({ $set: { "meta.lastRemoteAddress": {
address: context.remoteAddress
date: new Date()
} } }))

And then you just access meta.lastRemoteAddress

**Comment by schmidsi** [comment]
> Mutation in the type name is propably wrong because it should be independent from the api package.

I understand your point. So how can we access the `remoteAddress` in a module? Do you remember that PR: https://github.com/unchainedshop/unchained/pull/134 it was ugly because I had to hand down the `trackerContext` through all functions. Another solution would be to fire events at the beginning of every mutation with the tracking info. And then later search that event somehow. That was the idea behind `ADD_TO_CART_MUTATION`.

> I'd strictly distinguish:
> Logs -> Arbitrary messages, Untyped with Severity
> Events -> Typed, Semantic, no Severity/Level

Fully agree!

> 
> So if you need that I'd go with
> 
> ```js
> EventModule.findEvents({ type: "PRODUCT_ADDED_TO_CART", cartId: "asdf" });
> ```
> 
> Or
> 
> ```js
> EventModule.on("PRODUCT_ADDED_TO_CART", (userId, context) => Users.update({ $set: { "meta.lastRemoteAddress": {
> address: context.remoteAddress
> date: new Date()
> } } }))
> ```

I like that solution. Very composable.

> 
> And then you just access meta.lastRemoteAddress

**Comment by schmidsi** [comment]
@Mikearaya This is done, right?

**Comment by Mikearaya** [comment]
@schmidsi yes
