### ISSUE TITLE
Reporting Dashboard

### ISSUE THREAD

**Issue by fliptation** [unchainedshop/unchained#166]
# Reports

* Authors: @pozylon
* Status: **Draft**
* Breaking: No

## Introduction

Reporting Dashboard in Unchained Admin Panel

## Motivation

Unchained users currently can't see a big picture of the orders that get processed
through the system.

## Proposed solution

Very simple Dashboard style index page for admin ui with some nice charts
that show the performance of the shop.

## Detailed design

Tasks:

- [ ] Define what charts we want to show in the first place and how far we should go
- [ ] Chart library evaluation
- [ ] Dashboard Page Design in Admin UI
- [ ] New admin queries to get data needed if that's the case at all

## Alternatives considered

* Don't implement it in the engine/admin ui and do the reporting directly against the database with some kind of data mining tool.

**Comment by pozylon** [comment]
beeing implemented with new admin ui

**Comment by pozylon** [comment]
Currently beeing built in admin ui, requirements there.
