### ISSUE TITLE
Reconsider using "Subscription" as a top-level type

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#172]
I think there is a GraphQL convention that the top level type "Subscription" is used for GraphQL subscriptions with WebSockets. The top level types are: "Query", "Mutation" and "Subscription"

We are using this name for the new subscription-feature. Subscription in an e-commerce sense like: Regularly send me this products: 
https://github.com/unchainedshop/unchained/blob/master/packages/api/schema/types
/subscription.js#L51

But this leads to a misinterpretation in the Schema explorers:
<img width="967" alt="Screenshot 2020-05-20 at 12 09 54" src="https://user-images.githubusercontent.com/103280/82434640-714d9000-9a93-11ea-9a2c-87c32a1199b4.png">

<img width="419" alt="Screenshot 2020-05-20 at 12 15 29" src="https://user-images.githubusercontent.com/103280/82434764-a528b580-9a93-11ea-8bc0-b1845e2910f8.png">

**Comment by pozylon** [comment]
- Enrollment
- Membership
- Season
- Contract
- Lease
- Rental

**Comment by pozylon** [comment]
@Mikearaya @schmidsi @macrozone @claudiocro @schmidsi @harryadel Please vote

**Comment by schmidsi** [comment]
+1 for Enrollment

Other possibility: PlanSubscription

**Comment by macrozone** [comment]
whatabout ProductSubscription?

**Comment by Mikearaya** [comment]
+1 ProductSubscription

**Comment by harryadel** [comment]
We need to denote that it's a subscription so +1 [Plan || Product]Subscription
