### ISSUE TITLE
mutation.removeBookmark doesn't allow the same user that created the bookmark

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#182]
**Describe the bug**
when logged is as a normal user and trying to remove bookmark that I created using `removeBookmark` mutation i get the error `user with id xxxxxxxxx is not allowed to remove bookmark` error.
**updated** 
creating a bookmark with an anonymous user is not working currently also. when working properly `bookmark` mutation should call `loginAsGuest` whenever a user tries to bookmark an item without login and complete successfully.

**To Reproduce**
1. create a bookmark as a normal/guest user
2. try to remove that same bookmark
3. See error

```
Unhandled Runtime Error
Error: GraphQL error: The user "Ln8ambb28fYPs3zfd" has no permission to perform the action "manageBookmarks"
```

**Expected behavior**
users should be able to remove bookmark they created

**Screenshots**
![Screenshot from 2020-06-11 17-01-21](https://user-images.githubusercontent.com/9751246/84394312-72db2580-ac05-11ea-9682-1d49b4c5aae0.png)

 - OS: Ubuntu 20.04
 - Browser  chrome

**I have created a  [branch](https://github.com/unchainedshop/unchained/tree/bookmark-tests) with failing test simulating this scenario related with pull #183. please :bowing_man:  work on that branch**

**Comment by pozylon** [comment]
@toinhao1 You can go for this if you like

**Comment by toinhao1** [comment]
@pozylon sounds good, I'll try to resolve this over the weekend.

**Comment by toinhao1** [comment]
I have got pretty stuck on the first issue of a loggedIn user not able to removeBookmark. It seems isOwnedBookmark is not returning the correct value:

`role.allow(actions.manageBookmarks, () => isOwnedBookmark);`

As when I hard code it with true the test passes without a problem. Then I get stuck trying to figure out the values that isOwnedBookmark are returning. 

 A push in the right direction would be greatly appreciated.

**Comment by pozylon** [comment]
@toinhao1 You're totally on the right track,  if isOwnedBookmark returns a boolean, I'd search for the isOwnedBookmark, log inside the function so see what happens and maybe compare it to other "manageBookmarks" secured mutations that work like they should.

**Comment by toinhao1** [comment]
Thanks @pozylon, thats where I got stuck as when trying to console log within isOwnedBookmark, it does not log anything:

`  const isOwnedBookmark = (root, { bookmarkId }, { userId }) => {
    console.log(bookmarkId, userId) // eslint-disable-line
    const bookBool =
      Bookmarks.find({
        _id: bookmarkId,
        userId,
      }).count() > 0;
    console.log(bookBool) // eslint-disable-line
  };`

Or either here to see what is passed into loggedIn:

`export const configureRoles = ({ additionalRoles = {} } = {}) => {
  Object.entries(additionalRoles).forEach(([key, val]) => {
    allRoles[key] = new Roles.Role(key);
    val(allRoles[key], actions);
  });
  all(roles.ALL, actions);
  console.log(roles.LOGGEDIN, actions) // eslint-disable-line
  loggedIn(roles.LOGGEDIN, actions);
  admin(roles.ADMIN, actions);
};`

for all() and admin() both of those are hard coded, true for admin and false for all.

Also it seems we do not use the createBookmark mutation itself we use bookmark which then calls createBookmark or removeBookmark from within it. createBookmark is the only other mutation that utilizes the manageBookmarks action.

**Comment by toinhao1** [comment]
@pozylon This is seeming to make less and less sense, perhaps since I have not worked with unchained before I am not understanding the need for some things.

The mutations createBookmark and removeBookmark are called from within the bookmark mutation. With bookmark it is controlled by the actions.bookmarkProduct which is set to true as default for Admin and Users. 

If you can remove or create a bookmark with the mutation bookmark then why are we using the removeBookmark mutation by itself? 

Since also trying to use createBookmark with a normal User comes back with the same permissions error, which makes sense since there is no bookmark in the DB to check if isOwnedBookmark is that users.

**Comment by pozylon** [comment]
- createBookmark allows you to set a bookmark for a specific foreign user if you've got the access rights to do so (like admin), also removeBookmark shoukd work for bookmarks that are owned by foreign users.
- bookmark is a convenience method that allows somebody to simply toggle the bookmarked state of a product for the logged in user.

Indeed, this might be confusing and using createBookmark and removeBookmark is propably unnecessary complex. Maybe it's better to extend bookmark with an optional userId parameter for the admin cases.

**Comment by pozylon** [comment]
Fixed
