### ISSUE TITLE
Add tag field to media texts

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#184]
**Introduction**
it would be great if each media file for a product have a tag field to differentiate them from each other or to add trivial information about the media

**Solution**
Add tag field on media texts property

**Context**
this can be good for example if we have different files associated with a product backend can easily communicate with the front end to describe what this file represents

**Comment by pozylon** [comment]
@Mikearaya good idea in general. one change i request:

In Unchained, tags are always stored non-localized, and "labels" is used for localized tag like behaviour. Either you use labels instead of tags or you store the tags on the ProduceMedia (I guess there is already a tags field their but it's not used in the CP yet)

**Comment by Mikearaya** [comment]
@pozylon yes there is a tag on ProductMedia but this issue is related to adding differentiation between ProductMedia elements and the tags filed on ProductMedia. however, a label can do the job trick too like you said but there is no label field on the ProductMedia field currently too.

**Comment by pozylon** [comment]
Call me stupid but I don't see the problem yet.

Currently, we have "tags" on ProductMedia which allows you to differentiate between ProductMedia elements on a Product. ProductMedia are links between Product and Media and a tag is not localizable in unchained.

ProductMedia are 1 - n to ProductMediaText, so for different locales you have different localizable strings. If you put something on the texts field (= ProductMediaTexts type), you have to set it for every language.

```
ProductMedia:

_id: ID!
tags: [String!]
file: Media!
sortKey: Int!
texts(forceLocale: String): ProductMediaTexts

ProductMediaTexts:

_id: ID!
locale: String
title: String
subtitle: String
```

**Comment by pozylon** [comment]
@Mikearaya Is that still an issue or is it fine if I'm going to close this?

**Comment by Mikearaya** [comment]
@pozylon this issue was raised when the need to differentiate product media type came up eg (JPG, pdf,word) etc...
The exact scenario was we needed to differentiate product condition report which is pdf from product image.
How is this achieved currently??

**Comment by pozylon** [comment]
That‘s what I say, the tags field already exists and is used for these cases at veloplus and weng (check my comment above)
