### ISSUE TITLE
Siblings should support filtering out inactive products

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#185]
Product.siblings currently does not take "includeInactive" and always returns inactive products, too. This should work the same like for all other product array returning fields

**Comment by toinhao1** [comment]
Haha, I was working on this and now see you just closed it.

**Comment by pozylon** [comment]
@toinhao1 Oh sorry :) If you want you can drop by for a beer, maybe that helps (Florastrasse 58)

**Comment by toinhao1** [comment]
No worries! I will for sure another time.

**Comment by toinhao1** [comment]
Don't we need to add the new param in the example/control-panel schema?

https://github.com/unchainedshop/unchained/blob/cd2f8d65ddbd4ba2a086f24855e53dc7dc7ef257/examples/controlpanel/schema.json#L16189

**Comment by pozylon** [comment]
Yeah, that's totally out of date, thanks, will do
