### ISSUE TITLE
Improve Integration Test Surface

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#189]
We have added a lot of checkboxes @ https://github.com/unchainedshop/unchained/issues/37. Now we also have a lot of tests but it's unclear how far we want to go with the integration tests. Also based on the decision about that test strategy, we will have to analyze the whole API and find out where we need to add more tests and more test cases.

**2 Examples of different "level of test depth"**

Just tests that addCartQuotation does not return an error:
https://github.com/unchainedshop/unchained/blob/master/tests/cart-quotations.test.js

Tests the whole payment process, valid and invalid payments, checks the db and the returning fields for feasability, also checks the underlying mongodb collection for certain data (https://github.com/unchainedshop/unchained/blob/master/tests/plugins-datatrans.test.js#L185):
https://github.com/unchainedshop/unchained/blob/master/tests/plugins-datatrans.test.js

I'm proposing the following approach:
- [x] Find out which mutations and queries are not tested at all and list those
- [x] Define general rules about what **integration** tests should test and what they should not test
- [ ] Apply the rules to all existing tests and create a github issue labeled with "good first issue, tests-needed" for every missing/insufficient test

@schmidsi @claudiocro @macrozone @Mikearaya Any ideas or feedback from your side?

**Comment by Mikearaya** [comment]
This Are the queries and mutations that don't have any tests currently 

### Queries
- [ ] product
- [ ] products
- [ ] subscription
- [ ] subscriptions
- [ ] work


### Mutations
- [ ] activateSubscription
- [ ] addProductMedia
- [ ] heartbeat
- [ ] markPaymentCredentialsPreferred
- [ ] removePaymentCredentials
- [ ] removeWork
- [ ] setUsername
- [ ] terminateSubscription
- [ ] updateProductPlan
- [ ] updateSubscription

**Comment by Mikearaya** [comment]
In my opinion testing, all scenarios would be great
- Testing for success when passed the expected data and also failure when passing invalid data.
- Test all possible scenarios where the endpoint should fail and also check if it's failing for the right reason, meaning not only checking if the `error` array contains something but for that specific error it should be returning.
- touch all conditions the request might pass `(if/else)`
- Finally, all endpoint that require special privileges  should be tested at least ones with a user that doesn't have that privilege

**Comment by pozylon** [comment]
> Finally, all endpoint that require special privileges should be tested at least ones with a user that doesn't have that privilege

I like this very much.
