### ISSUE TITLE
Transactional E-Mails through Mailchimp

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#193]
**Introduction**
Currently, the only HTML/CSS left in unchained engine is the E-mails generated out of the box for account management and order confirmations. This is technically error prone and against the headless approach.

**Describe the solution you'd like**
We should consider using Mailchimp for E-Commerce Mailing stuff, this allows a customer to edit mail templates by their own

**Describe alternatives you've considered**
Is there an Open Source Software or Europe-based SaaS that allows for similar CRM like tasks and E-Mail Designer like Mailchimp offers?

**Features**
- [ ] Send standard transactional emails like: password confirm, password reset, order confirmation, order updates, etc.
- [ ] Integrate CRM solutions for automatic emails like: abandoned cart, special offers for the n-th order, special offer for total revenue per customer, ...

**Comment by schmidsi** [comment]
https://mailchimp.com/developer/guides/getting-started-with-ecommerce/

**Comment by pozylon** [comment]
Looking at the documentation this seems like a perfect case for a Sync Tool living on it's own right, we could even use Swift, Go, Rust or Deno to do it :)

**Comment by schmidsi** [comment]
Yeah, right. It's actually two almost completely different tasks: Transactional mails and syncing e-commerce data with third-parties.

**Comment by pozylon** [comment]
I've renamed this issue so it's the pot for "transactional e-mails through mailchimp". The e-commerce tracking should be handled in a different ticket.

**Comment by pozylon** [comment]
We did not implement transactional mailing through mailchimp but we have introduced an even more flexibel messagin approach where we can connect to any mailing backend, so i consider this as done
