### ISSUE TITLE
[api] Business logic at wrong abstraction level

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#2]
Sometimes, implementation details of core-modules are implemented in the resolvers. Not clean code at all.

Good (removal logic is hidden from API):
https://github.com/unchainedshop/unchained/blob/master/packages/api/resolvers/mutations/removeDeliveryProvider.js

Bad (removal logic is implemented by the API layer):
https://github.com/unchainedshop/unchained/blob/master/packages/api/resolvers/mutations/removeProduct.js

**Comment by macrozone** [comment]
currently, most business logic is inside collection-helpers, which is also dependent on the framework. its best to make the business logic framework agnostic.

**Comment by pozylon** [comment]
@macrozone please have a look at #4, that is the "make-stuff-framework-agnostic" issue

**Comment by macrozone** [comment]
@pozylon i added a comment there, where i discuss in what i think is the most important refactoring area.

**Comment by pozylon** [comment]
Closing in favor of #115
