### ISSUE TITLE
Controlpanel Users View: Sorting/Filtering/Statistics

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#204]
# Introduction
As a Admin I want to see quickly the most important information about my user base:

- How many registered users are there
- How many have already a confirmed email address
- Which are the newest users
- Which are the guest accounts
- ...

# Describe the solution you'd like
The solution in my mind would be on top of the user list the possibility to sort and filter the list and display the count of the sorted result.

Filters would be:
- Guest/Registered (existing)
- Email-Confirmed
- ...

Sorting options:
- Registration date (default descending)
- Last login
- ...

# Describe alternatives you've considered
Quickwin without sorting/filtering would be just default sort order registration date ascending and display the key metrics: total users, total guests on top of the column.

# Additional context
A general sorting/filtering functionality could be used on other list-views as well.

**Comment by fliptation** [comment]
@Mikearaya can we have this in admin-ui please?

**Comment by Mikearaya** [comment]
@fliptation sure we can, most of them are already implemented already and the remaining can be included after we close this issue #436

**Comment by pozylon** [comment]
Closed, admin ui
