### ISSUE TITLE
Get rid of "meteor/percolate:migrations"

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#213]
- [x] Remove all traces of percolate:migrations
- [x] Make an own minimal migration tool and put that into the utils package
- [x] Make all the migrations work and TEST if they run trough properly.
- [x] Migrations should only run when the env variable UNCHAINED_DISABLE_WORKER is falsy

**Comment by harryadel** [comment]
Relevant: https://github.com/reactioncommerce/migrator
