### ISSUE TITLE
Get rid of "aldeed:schema-index"

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#216]
It's not the job of a schema validator or collection2 to automatically create indexes based on a flax index: true.

- [x] Remove all traces of aldeed:schema-index
- [x] Change all schemas that contain index: true and add explicit index creating code for all collections that had index: true flags. See the core-worker/db/schema.js file for example

**Comment by Mikearaya** [comment]
@pozylon default sort order will be ascending? if I'm correct.

**Comment by pozylon** [comment]
Nice, first part of meteor purge is done
