### ISSUE TITLE
Get rid of Meteor Accounts

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#225]
Alternative frameworks we have looked into:
- Accounts JS https://github.com/accounts-js/accounts (thanks @harryadel )
- Ooth https://github.com/nmaro/ooth (maybe fork?)
- Passport (http://blog.thebakery.io/meteor-accounts-auth-with-passportjs/)

Decision: Accounts JS (maintained and modern)

Requirements for Meteor Accounts Hop-Off / Purge:

- [ ] Existing cookies / tokens should still work after migration, so that we don't have to invalidate all user sessions when upgrading a client, luckily accountsjs seems flexible enough (https://www.accountsjs.com/docs/api/server/interfaces/accountsserveroptions#optional-createnewsessiontokenonrefresh, https://www.accountsjs.com/docs/api/server/interfaces/accountsserveroptions#optional-tokencreator)

- [x] Is 2FA ready and supports different strategies

- [ ] Easy way to extend user fields

- [ ] Documented migration path for custom login handlers and events (Accounts.registerLoginHandler, Accounts.onLogin) (https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js) to Accounts.js as we currently use these features for different clients

**Comment by pozylon** [comment]
First we will need some kind of migration path :)

**Comment by harryadel** [comment]
If it's ok with you I may start tinkering and see where it leads.

**Comment by pozylon** [comment]
Sure thing, thanks

**Comment by harryadel** [comment]
The plan is as follows:

[] Tackle login and user-creation - the corner stone of any working authentication module and also this ensures we don't break the authentication for current users.

[] Replace the other functions like password reset, password change etc. This could be split up into PRs with each one only undertaking one function. Instead of major PR containing all of the changes. 

[] Remove Meteor accounts/base package and test for any errors.

It's important to note that with each change the associated hooks should be changed as well.

**Comment by pozylon** [comment]
Nice, just one remark: I‘d go one step further and define milestone 1 to be login only. So user creation still through meteor accounts. Then you could proof that login with legacy hashes work

**Comment by stolinski** [comment]
This might be an odd question for this repo considering I'm not using unchained. But have you had luck with accounts.js logging into Meteor accounts? I have a very similar setup to your accounts branch, but am not getting creds to validate. Sorry for making an off topic post in your repo, but I'd love some help with my implementation as it's VERY similar to yours.

**Comment by harryadel** [comment]
Hey Scott! Big fan. As you're know accounts-js relies on an entirely different mechanism for authentication that utilizes JWT which isn't compatible with the current login system in Meteor accounts, so we had to extend `AccountsServer` and override the current `loginWithUser` as with with `logout` method too.  

https://github.com/unchainedshop/unchained/blob/new-accounts/packages/core-accountsjs/core-accountsjs.js#L121

**Comment by stolinski** [comment]
I've been pawing around your core-accounts package to base some of my code, but the main issue I'm hitting is in comparing the password and hash that's currently in the db. In an older version of accounts.js I used `const password = new AccountsPassword({ passwordHashAlgorithm: 'sha256' })` but it seems like passwordHashAlgorithm isn't an option anymore. Reading the docs it seems like I need to write a custom compare, but I didn't see anything like that in your codebase. I was wondering if your compare was working as is currently.

**Comment by harryadel** [comment]
The compare does work. I don't know about the old version you're describing but as it appears you had to pre-hash your passwords with sha256 before bcrypt comes into play as is the case with Meteor methods. This part gets done outside of core-accountsjs package [here](https://github.com/unchainedshop/unchained/blob/new-accounts/packages/api/resolvers/mutations/accounts/loginWithPassword.js#L14).

**Comment by stolinski** [comment]
It's interesting that makes so much sense. I JUST got it working now, basically copied Meteor's own getPasswordString function after checking the old version of accounts.js. Thank you for this diversion of your issue. I'll bow out now. Thank you so much for your time.
