### ISSUE TITLE
Possibility to search for an user in the Controlpanel

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#226]
**Introduction**
As an admin I want to be able to search for users by typing their name in order to quickly find the user and inspect its current state.

**Is your feature request related to a problem? Please describe.**
Currently, the `users(...)` query is not able to receive search params

**Describe the solution you'd like**
It would be possible without changing the GraphQL Query with a client-side in-memory search but that solution would not scale.

**Describe the design of the solution in detail**
Extend users-query:
```graphql
users(
limit: Int = 20
offset: Int = 0
includeGuests: Boolean = false
queryString: String # <- new
): [User!]!
```

This query string would result in a simple MongoDB query in the fields: `username`, `name`, `emails` and maybe also `userProfile`.

Then, use this extended query to have search field in the controlpanel on top of the users-list. Typing in this field would filter the userlist below.

**Comment by pozylon** [comment]
@schmidsi The frontend part should also be part of the solution, right?

**Comment by schmidsi** [comment]
Yes
