### ISSUE TITLE
[FEATURE REQUEST] Disable initialisation of providers on carts on every instance restart

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#236]
**Introduction**

unchained iterates over all carts (orders) on start and tries to sanitize the current selected providers.
The idea is that carts always have valid providers, e.g. after one has been removed

**Is your feature request related to a problem? Please describe.**

initialisation of providers calls a filter function that can be used to define which providers are available for a customer. e.g. disable certain payment providers if the user is not considered credit worthy. These checks can be expensive (both computational and money), so they have to bee called as rarely as possible.

Currently the filter function is called very often, e.g. whenever you fetch providers through graphql, so every expensive call has to be cached.

Additionally, unchained re-initialize all open carts whenever an instance starts. That is very problematic, because the list of open carts will often grow and will contain staled carts. As the filter function does not know why it is called, you can not reliably tell whether you should call these expensive functions.

in scaleable cloud infrastructures its even worse as instances might come and go. its in general advisable to not touch the database at all on instance starts. Migrations and background jobs should be done in a specific instance

**Describe the solution you'd like**

I would argue that this mechanism of re-initialize the providers on open carts is not worth the drawbacks, I would argue that any consumer of the current cart properties should deal with the situation where the current selected provider is invalid. For frontends, thats usually not a big deal as you can simply tell the users to select a payment provider. Most checkout user flow will handle this. The second consumer is the checkout mutation. This probably should just throw an error when no payment or delivery provider is selected.

**Describe the design of the solution in detail**

see above.

**Describe alternatives you've considered**

setting a valid payment provider could also be done lazily when calling it and it is invalid. That would be even better than the current solution as providers can become invalid at any time (= they get deleted in the db) 

**Additional context**

**Comment by pozylon** [comment]
@macrozone How would you feel if we just allow you to disable the invalidation on startup for now and then find better ways in #332 ?

**Comment by pozylon** [comment]
Possible with beta
