### ISSUE TITLE
"Request entity too large" When Accessing Assortments in CP

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#238]
**Describe the bug**
The Controlpanel's Assortment List is empty

**To Reproduce**
1. Login to CP
2. Click on Masterdata -> Assortments
3. List is empty

**Expected behavior**
It should show the root asssortments.

**Additional context**
"Request entity too large" in Network Tab

**Comment by harryadel** [comment]
Unable to reproduce. I've tried also connecting to bitbook API using: 
`cd examples/controlpanel && GRAPHQL_ENDPOINT=https://unchained-test.bitbook.education/graphql npx next -p 4000`

**Comment by pozylon** [comment]
Me neither :S
