### ISSUE TITLE
Refactor E-Mail Template System

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#24]
it should possible to show more infos on the delivery email like:

- customer email and other infos
- deliveryContext stuff

**Comment by fliptation** [comment]
this would also be helpful on the order confirmation page.

**Comment by pozylon** [comment]
Let's continue the discussion about refactoring the mail template system here
https://github.com/unchainedshop/unchained/pull/39

**Comment by pozylon** [comment]
Closing in favor of #115
