### ISSUE TITLE
do not throw error when resource is not found

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#246]
**Describe the bug**

current unchained started to throw errors when a product or assortment is not found.

I have not a final opinion on that, but it seems to be an antipattern because it does not add any information to clients but rather makes stuff more complicated: https://stackoverflow.com/a/54641803

e.g. SSR will always throw errors when one request has an error, which is really annoying

**To Reproduce**

**Expected behavior**

resource not found should not throw an error but return null as before

**Comment by macrozone** [comment]
there is also a case for having infos in the errors field: https://stackoverflow.com/a/57462949

so no conclusion for me. 

I think make errors more obvious is not a bad thing, but it should not break when errors were expected. E.g. user provided slugs etc.

**Comment by schmidsi** [comment]
I think this is a bug. We refactored the internal errors to be more meaningful and this might have introduced this issue. As far as I understand the GraphQL spec: It should try to always respond and only throw if there is a fatal error on the server side. Like DB-connection interrupted.

But, I like the idea of having both a `data` and a `errors` fields in the response, as long as there was no fatal error on the server side. But this would possibly require changes on the front-ends, since a lot of developers have the following mind-pattern:

> If there is an error, there is no data and therefore we do not display anything.

It should be shifted to:

> If I have some data, display it.

**Comment by macrozone** [comment]
> I think this is a bug. We refactored the internal errors to be more meaningful and this might have introduced this issue. As far as I understand the GraphQL spec: It should try to always respond and only throw if there is a fatal error on the server side. Like DB-connection interrupted.
> 
> But, I like the idea of having both a `data` and a `errors` fields in the response, as long as there was no fatal error on the server side. But this would possibly require changes on the front-ends, since a lot of developers have the following mind-pattern:
> 
> > If there is an error, there is no data and therefore we do not display anything.
> 
> It should be shifted to:
> 
> > If I have some data, display it.

indeed, there is also the errorPolicy option in apollo client to decide on what to do when there is an error.

Problem in our project is, that we have some branching logic based on wether an url path segment is an assortment or a product. this will now always trigger errors

**Comment by Mikearaya** [comment]
this is not a bug, `assortment` or any resource requested by id is still returned as `null` when it's not found but now there is more clarity as to why it is null that give front-end more information to display an appropriate message based on the `error` returned from the server.

**Comment by macrozone** [comment]
@Mikearaya maybe its intentional, but it will break many project. In particular it breaks SSR in many cases

**Comment by pozylon** [comment]
@macrozone I can't follow why it breaks SSR but indeed, we have to think about this :S Especially Query.assortment and Query.product are wrong at the moment because they allow to send null schema-wise but throw an error instead.

**Comment by pozylon** [comment]
@Mikearaya Sure it's null, maybe "data" is null because error is not?

**Comment by pozylon** [comment]
I think it's definetely fine to throw an error when a user has no access to do something (acl) or if somebody just sends invalid combination of data, like when a mutation with 2 optional parameters requires one or the other (_id or slug) it's fine to throw and say you cannot provide both or you have to send at least one. Also it's fine to throw if somebody tries to get an assortment with an id of null or a particular object has the wrong state (a CONFIRMED cart cannot be checked out for ex.).

On the other hand, if you submit a valid _id to a Query.entity query, the result should be:

Variant 1:
Query.entity(...) : Entity! + throws error if not found

Variant 2:
Query.entity(...) : Entity + send null if not found
Same is true if a list is returned, it should always be [Entity!]! and if 0 products are found, an empty array is correct.

From this point of view, Variant 2 seems more consistent.



Can you guys agree to this?

**Comment by pozylon** [comment]
I personally dislike the idea of having "Result" types on Mutations or Queries because then you have to tackle errors in two ways as the exceptions still exist.

**Comment by macrozone** [comment]
> @macrozone I can't follow why it breaks SSR but indeed, we have to think about this :S Especially Query.assortment and Query.product are wrong at the moment because they allow to send null schema-wise but throw an error instead.

to be precise: we had some queries where it was "expected" that the query will return null. Also there are some user-generated props that would trigger queries.

now these queries will trigger an error. Without further adjustments the normal SSR function will stop rendering if an error occures. You have to set `errorPolicy: "all"` to prevent this.

I could avoid some of these problems now, but still i think its valid to ask for data that does not exist (anymore). Be aware that these errors will also appear in the unchained log alongside other, much severe errors. Maybe that is a good thing in some cases, but developers should know that they are not allowed to ask for data that does not exist anymore.

Maybe comprimise would be to not log that as an error in unchained and still throw an error to the client

**Comment by schmidsi** [comment]
> this is not a bug, `assortment` or any resource requested by id is still returned as `null` when it's not found but now there is more clarity as to why it is null that give front-end more information to display an appropriate message based on the `error` returned from the server.

I wasn't aware of this. I also think it is ok to send the `errors` field even if the query returns something. But I also see the point of @macrozone that it is a breaking change and we need to be careful.

I also agree with @pozylon Variant 1 and Variant 2. But still the question remains, if Variant 2 should send some information in the `errors`-field, if a query returns null.

So my gut-feeling currently is, also after reading this: http://spec.graphql.org/draft/#sec-Errors -> It is generally ok to send errors alongside data and the front-ends need to handle this. But a simple "no object with ID x" found, is not an error that needs to go there, because that is what `Query.entity(...) ` -> `null` already implies: Object not found. That should also not be logged as an error. But as @pozylon said, if it is a ACL or other invariants violation, then it should populate the `errors` field.

**Comment by pozylon** [comment]
Excellent content at http://spec.graphql.org/draft/#sec-Errors

**Comment by pozylon** [comment]
I think after reviewing the comments and trying to summarize we can say that looking at the example of Query.user:

Query.user(userId...) should:
1. Return an error if the user is not allowed to query for foreign users
2. Return null if the user has not been found without sending an error
3. Return an error if the provided id is invalid or any other internal error occured
4. Return the user if the object has been found and the user has the correct permissions

**Comment by pozylon** [comment]
Another example for Query.assortment:

```
assortment(assortmentId: ID, slug: String): Assortment
```

1. Return an error if neither an assortmentId nor a slug is provided
2. Return an error if both assortmentid and slug is provided
3. Return an error if the provided input is invalid
4. Return null if a valid assortmentId or a valid slug is provided but no assortment has been found
5. Else return the found assortment

**Comment by pozylon** [comment]
Another example:
```
      productReview(productReviewId: ID!): ProductReview!
```

Fix the query to return null if review not found and make returned type optional in schema:

```
      productReview(productReviewId: ID!): ProductReview
```

**Comment by pozylon** [comment]
For all mutations:
1. providing an id of a non existent entity should throw 
2. the type that is returned should be non-optional

So mutation resolvers will most likely stay as is

**Comment by schmidsi** [comment]
> Another example:
> 
> ```
>       productReview(productReviewId: ID!): ProductReview!
> ```
> 
> Fix the query to return null if review not found and make returned type optional in schema:
> 
> ```
>       productReview(productReviewId: ID!): ProductReview
> ```

I generally agree and I'd like to point out to the special case that an API developer has: If you really type a query with a required return type like:

```gql
something(someId: ID!) Result!
```

then I expect this query to throw an error if `someId` is not found. So to be clear: We strongly discourage to do this if there is no really good reason for it. Right? Better have the result optional and solve this case (not found) in consumer code.
