### ISSUE TITLE
Get rid of "ostrio:files"

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#247]
How to do:

Phase 1: 
- New breaking GraphQL schema with new file upload feature

Phase 2: 
- Completely remove ostrio:files and core-files, build new files package from scratch
- Don't build support for GridFS & local files, only support S3-compatible signed object PUT uploads
- Removing a file metadata entry on MongoDB should remove the binary on the block storage

Phase 3:
- GridFS & local files

~~Approach 1 for Upload:~~
- ~~Client calls some kind of upload mutation, engine creates a signed PUT url, creates a mongodb entry for reference and returns the File object in a "ready for upload" state~~
- ~~Client directly PUT the file to that url, (how does the Unchained Engine find out about that the file has been PUT?)~~

Aproach 2 for Upload:
- Client calls some kind of prepareUpload mutation, engine creates a signed PUT url and returns the temporary PUT url
- Client directly PUT the file to that url, then calls the upload mutation with the uploaded URL

(Optional Phase 4):
- Find out how and when Media Entries get cleaned from the db, maybe add a worker that cleans up zombie media

Material:
https://github.com/prestonlimlianjie/aws-s3-multipart-presigned-upload/blob/master/README.md

**Comment by pozylon** [comment]
Current state of uploading files with Unchained:
```
scalar Upload
updateUserAvatar(avatar: Upload!, userId: ID): User
addProductMedia(productId: ID!, media: Upload!): ProductMedia!
addAssortmentMedia(assortmentId: ID!, media: Upload!): AssortmentMedia!
AssortmentMedia.file: Media!
ProductMedia.file: Media!

type Media {
  _id: ID!
  name: String!
  type: String!
  size: Int!
  url(version: String = "original", baseUrl: String): String!
  meta: JSON
    @deprecated(
      reason: "Due to ambiguity this field will be removed on future releases,Please write a custom resolver that reflects your business-logic"
    )
}
```

**Comment by pozylon** [comment]
Phase 1:

- Keep core-files, add new core-files-next package and add new mutations handled by the new package:
```
prepareProductMediaUpload(productId: ID!): String!
prepareAssortmentMediaUpload(assortmentId: ID!): String!
prepareUserAvatarUpload(userId: ID): String!
```

Keep all DB schemas and entities

The URL returned is a signed PUT the client can use to upload files

**Comment by Mikearaya** [comment]
@pozylon this workflow is good but how can the engine be sure the client has succeeded uploading. I think there should be a syncing method to find stranded MediaUploadTicket. and the webhook might be necessary.

**Comment by pozylon** [comment]
Ok, good point, we can configure mongodb in a way that the stranded db entries get removed which are expired TTL https://docs.mongodb.com/manual/core/index-ttl/

```
db.uploadtickets.createIndex( { "expires": 1 }, { expireAfterSeconds: 1 } )
```
