### ISSUE TITLE
BUG: can't add multipe products to cart in one request

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#26]

**Comment by pozylon** [comment]
maybe related: https://github.com/apollographql/apollo-link-state/issues/40

**Comment by macrozone** [comment]
@pozylon i tried that, but it resulted in inconsitent results, i sometimes got only one product and in some occasions three products, but i sent two. Have to revisist that, something was wrong.

**Comment by macrozone** [comment]
the bug is that `addCartProduct` will create a new order if no orderId is given or it tries to fetch one from the user. If you fire multiple `addCartProduct` at the same time, it can happen that both will create a new Order.

solution would be to adress the cart never by its orderId, but with something that is always consistent. Consider this:

- if you only allow 1 cart, its straight forward. The cart is always `Orders.findOne({userId, isCart: true})` (i know `isCart` does not exist, its in fact `{countryCode, status: { $eq: OrderStatus.OPEN }}` but you get the idea)

- if you want to have multiple carts, you have to give everyone a certain identifier, like its index (0 is always the default cart). If a user wants to add an item to a certain cart, he has to address this cart anyway somehow

Another solution would be to use mongodb transaction and try to lock the db from start of the mutation until the end. (or lock somehow the mutation. Meteor's older methods did indeed something like that: they were always sequential for a given user)
