### ISSUE TITLE
mutation.removeWork deletes all works nomatter there current status

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#262]
mutation.removeWork deletes all kinds of work nomatter there status but there is an error stating `WorkNotFoundOrWrongStatus` 
my question is when is a work not possible to be deleted?. if it can be deleted no matter its status what is the use of this error?

**Comment by pozylon** [comment]
No, only new and allocated work can be removed, see removeWork in core-worker/director.js
