### ISSUE TITLE
admin can mark preferred payment credential of other users

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#263]
i know this has a little to no repercussions but the admin can actually mark preferent payment credentials of other users using `mutation.markPaymentCredentialsPreferred`.  should we remove this privilege from admin?

**Comment by pozylon** [comment]
I think the admin should have rights to totally do anything even if it does not make sense in current cases. So we are consistent and if some kind of restricted-admin is needed, that can be done by adding a new role in a customer project with the explicit rights that role should have. @schmidsi @macrozone feel free to reopen this if you oppose this.

**Comment by schmidsi** [comment]
In this case I agree: admin should be able to change it. But we should not allow the admin to violate invariants through mutations.
