### ISSUE TITLE
updating single subscrition as normal user is possible but not reading

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#265]
**Describe the bug**
Updating a subscription as a normal user is possible but reading a single subscription is not, I think this contradicts. what do think about this?

**To Reproduce**
* try updating a single subscription as a normal logged in user (you will succeed)
* now try reading the same subscription as the same user (you will fail)

**Expected behavior**
if a user can update a single subscription I think the user should also be able to view it. otherwise, how is the flow going to be for a normal user to use this mutation?

**Comment by pozylon** [comment]
Absolutely, the ACL was wrong and used quotation checks, fixed now
