### ISSUE TITLE
unchained throws authorization error when i try to remove an non existing cart item

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#268]
**Describe the bug**

when i remove a cart item using 

```
mutation {
  removeCartItem(itemId: "xxxx-some-id") {_id}
}
```

it will throw an error

```
The user \"xxx-my-user-id\" has no permission to perform the action \"updateOrderItem\" in \"removeCartItem\""
```

the problem is now, that this looks identical to situation where you have no cart at all and need to login as guest.

the situation above is likely to happen if you use optimistic responses and a user might delete  cart item that has already been removed.

**To Reproduce**
1. call the mutation above with a non-existing itemId

**Expected behavior**

it should not throw a permission error. it would probably better if the mutation would require the orderId to be passed. Then you could throw a permission error if a orderId was passed that does not belong to the user and return a different error (or no error at all) if the orderId is ok, but the itemId does not exist

**Screenshots**

-

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser [chrome
 - Version 0.54.0

**Comment by pozylon** [comment]
This situation is true for other mutations and queries, for example when trying to get an order by id that the user has no access to.

It's always the case when there is a special permission check that depends on parameters. The ACL is conducted first and fails before the mutation code actually runs.

**Comment by pozylon** [comment]
Also, it's not quite true what you wrote:

The user \"xxx-my-user-id\" has no permission to perform the action \"updateOrderItem\" in \"removeCartItem\""

-> It's The user \"\" has no permission to perform the action \"updateOrderItem\" in \"removeCartItem\"" (always empty userId! when not logged in)

**Comment by pozylon** [comment]
I could change the error message to something more clear though:

Anonymous users are not allowed to perform the action \"updateOrderItem\" in \"removeCartItem\

**Comment by macrozone** [comment]
@pozylon that is not the issue. The issue is that unchained throws an error when the item happens to no longer exist and I - as a client - cannot differentiate that from the situation where unchained throws because i have no valid user.

I fixed the problem now by simply ignore the erorr with `errorPolicy: "ignore"`. Any other solution did not work properly, as it seems with optimistic responses you cannot just do try catch.

In general with caching and optimistic reponses its always tricky to have the exact same state on the client as you have on the server. I guess i would be happy if a delete mutation is just idempotent and does not complain if the resource is already deleted.

**Comment by pozylon** [comment]
If we supported Idempotent mutations, we'd do that for all mutations not just for removeCartItem.

But still, I'm having trouble to grasp the problem, because we never had problems with the exceptions before, also when using optimistic responses. Can you try to explain the flow of data how to reproduce this?

I was thinking of:
1. fire removeCartItem, optimistic response immediately removes the item from the cart which disables any double posting?
2. removeCartItem returns with success
3. sane state

And maybe:
1. Cached cart
2. Fire removeCartItem, optimistic response immediately removes the item from the cart
3. removeCartItem returns with error -> reset your store, cart get's updated
4. sane state

**Comment by pozylon** [comment]
I've changed the ACL checks that if a provided entity does not exist at all, the acl checks pass with true giving the resolvers the possibility to early exit with a not found error
