### ISSUE TITLE
addCartProduct should return cart

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#27]
sorry, i forgot about that one.

If i call `addCartProduct` i have to to use `refetchQueries` to see the new cart items, because apolloClient does not know what to do with the new OrderItem that gets returned from `addCartProduct`

if we would return the new cart, we could have the correct cart on the client in one request.

in general, every mutation that changes the cart/order should return an `Order`

**Comment by pozylon** [comment]
OrderItem has a field named "order" which you can explode so you don't need to use refetchQueries.

```
mutation {
  addCartProduct(orderId: "...", productId:"...") {
    order {
      _id
      items {
        _id
        
      }
    }
  }
}
```


I like the concept of "every mutation that changes an order should return the order". And then there is that other concept where you introduce types for every mutation result which also attracts me.

**Comment by macrozone** [comment]
`where you introduce types for every mutation result which also attracts me.` yeah!
