### ISSUE TITLE
[FEATURE REQUEST] Extended Work Queue

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#274]
Currently you cannot filter the Work Queue in the Controlpanel. Sometimes it's important to filter certain work types and status in the Work Queue to dig into problems.

**Comment by pozylon** [comment]
https://git.panter.ch/manul/vps/veloplus-shop/-/issues/836

**Comment by harryadel** [comment]
Cannot access the link. Can you at least pull me a screenshot?

**Comment by pozylon** [comment]
Sorry, the link is not relevant it just says that they want that feature and it makes sense. Basically the work queue should be filterable by type and status.
