### ISSUE TITLE
automatic logout interval too fast

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#283]
currently, the user is getting logged out of the control panel after a few minutes. while this feature might be useful in some scenarios I think the current implementation interval is very short and is kind of annoying when you get logged out in the middle of a task.

if it's possible to increase the interval to at least half a day or even better when the system is idle i.e. without receiving any request from the client for a certain period. if not remove this feature entirely

**Comment by pozylon** [comment]
I think this is related to the new accounts package, before the logins where valid for 30 days, @harryadel can you look into this?
