### ISSUE TITLE
Doc or Page Broken/Unavailable Links in Readme.md

### ISSUE THREAD

**Issue by shubham-kaushal** [unchainedshop/unchained#291]
**Describe the bug**
Doc or Page Broken/Unavailable Links in Readme.md

**To Reproduce**
https://github.com/unchainedshop/unchained/blob/master/docs/architecture.md
https://github.com/unchainedshop/unchained/blob/master/docs/code_of_conduct.md
https://github.com/unchainedshop/unchained/blob/master/docs/contributing.md

**Expected behavior**
Replace it with Correct/Available URL

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pozylon** [comment]
Fixed
