### ISSUE TITLE
Better TypeScript support

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#297]
Since #146 we have now basic Typescript support. But we need to enhance it at some point. I see 3 main directions that we can go now:

1. **Enhance and add more `d.ts` files**. This is unobtrusive and does not change the code at all.
2. **Expose and publish the types**: We need to find a way so that a consuming project can use the types. I assume that type definitions are not part of the atmosphere package. So we need to find a way to generate a types-only package and publish it, so consumers can install it like: `npm install --save-dev @unchainedshop/types`.
3. **Rewrite current code with Typescript**: This is the last step and not so important at the moment in my opinion.

**Comment by macrozone** [comment]
@ses if you do 3. with most public functions, you don't have to write d.ts files manually. I think d.ts files easily get out of sync and are annoying to write. They are more a band-aid.

if you rewrite files to ts, everything will eventually fall into place.

you can create definition files automatically with tsconfig.json --> "declaration": true

**Comment by schmidsi** [comment]
I agree. `d.ts` files are bandaid and should be removed in the long run. But it gives us some speed now to gradually improve.

**Comment by pozylon** [comment]
Implemented by #402 👏👏
