### ISSUE TITLE
setUsername should allow normal users to update there name

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#303]
currently, only users with admin privilege are able to update their username and call to `mutation.setUsername` with normal user privilege throws permission error. 
Normal users that are not gues should be able to update their username using this endpoint.

**Comment by pozylon** [comment]
Some thoughts about this: At the moment we have two clients where it's important that users cannot update their usernames him/herself.

```
updateEmail: acl(actions.updateUser)(updateEmail),
  addEmail: acl(actions.updateUser)(addEmail),
  removeEmail: acl(actions.updateUser)(removeEmail),
  updateUserAvatar: acl(actions.updateUser)(updateUserAvatar),
  updateUserProfile: acl(actions.updateUser)(updateUserProfile),
  setUserTags: acl(actions.manageUsers)(setUserTags),
  setPassword: acl(actions.manageUsers)(setPassword),
  setUsername: acl(actions.manageUsers)(setUsername),
  setRoles: acl(actions.manageUsers)(setRoles),
  enrollUser: acl(actions.manageUsers)(enrollUser),
```

And currently the ACL uses two permissions:
1. **actions.manageUsers** which is by default only allowed for administrators
2. **actions.updateUser** which is by default allowed for administrators or updating the logged in user

So now we could change the setUsername permission to actions.updateUser to implement that feature you're requesting which is going to be the right default for some clients but the wrong for others and hard to customize. If we had an action for setUsername like actions.updateUsername we could easily change the default behavior by putting the action into the loggedin role and call:

role.allow(actions.updateUsername, () => true);
