### ISSUE TITLE
catalogPrices are null for Czech users (and maybe others)

### ISSUE THREAD

**Issue by nabbl** [unchainedshop/unchained#330]
**Describe the bug**
One of our czech developers doesn't get any prices when querying products.

**To Reproduce**
1. Go to graphql playground
2. use `{ "accept-language": "cs,en;q=0.9,cs-CZ;q=0.8,sk;q=0.7,it-IT;q=0.6,it;q=0.5" }` as a header
3. query a product: ``` products {_id
    ... on SimpleProduct {
      catalogPrice {
        amount
      }
    }```
4. catalogPrices is null.

**Expected behavior**
Catalogprices are not null if at least one price is defined (disregarding any currency setting)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version newest

**Comment by pozylon** [comment]
Can you try setting the environment variables LANG and COUNTRY to isoCodes that exist in the db?

**Comment by pozylon** [comment]
Expected behaviour: Catalogprices are not null if at least one price is defined (disregarding any currency setting) for the currently active country

**Comment by Mikearaya** [comment]
@pozylon local dev env values are not getting picked [here](https://github.com/unchainedshop/unchained/blob/master/packages/utils/locale-helpers.js#L3) instead gets the values from my workstation and I get the same result if when accept-langues are changed
