### ISSUE TITLE
[FEATURE REQUEST] Use zodern:remove-client-js

### ISSUE THREAD

**Issue by harryadel** [unchainedshop/unchained#331]
As suggested in this blog [post](https://zodern.me/posts/optimize-meteor-ci/#minify), if our application doesn't have a client, we can use [zodern:remove-client-js](https://github.com/zodern/remove-client-js/) to remove all client js from production builds, removing the need to minify any code.

**Comment by pozylon** [comment]
closing because it will be obsolete with new npm-based deployment of v1
