### ISSUE TITLE
Invalid payment provider if user adds discounts and outstanding value is zero

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#332]
**Describe the bug**
During checkout the following situation was observed in one of our projects:

- User selects payment via credit card
- User adds a voucher to the cart -> outstanding value is now zero
- Now the credit card payment provider is not valid anymore: You cannot pay for 0 on most payment providers

Currently, this leads to a actual invariant: The selected paymentProvider is not part of the supportedPaymentProviders
```json
{
  "data": {
    "me": {
      "cart": {
        "payment": {
          "_id": "ZDFTomSCrF4agbWJq",
          "provider": {
            "type": "GENERIC",
            "interface": {
              "label": "Datatrans Legacy (https://docs.datatrans.ch/v1.0.1/docs/getting-started-home)"
            }
          }
        },
        "supportedPaymentProviders": [
          {
            "_id": "free",
            "type": "INVOICE",
            "interface": {
              "label": "Invoice (manually)"
            }
          }
        ]
      }
    }
  }
}
```

**Expected behavior**
The engine should switch to a valid payment provider. In this special scenario, maybe invoice and mark it as paid immediately? So my suggestion is to change the the result of the `addCartDiscount` mutation from `OrderDiscount!` to `Order`. That way, we can change the `order.payment.provider` inside of this mutation and a front-end can automatically update.

```graphql
addCartDiscount(
orderId: ID
code: String!
): OrderDiscount!
```

to 

```graphql
addCartDiscount(
orderId: ID
code: String!
): Order!
```

**Comment by macrozone** [comment]
the problem does not only apply to updating discounts. usually the filter provider function is defined in userland, so you can't know what can cause a provider to become invalid.


The best solution is  that cart.payment.provider resolves to null if it becomes invalid. In other words: that resolver should use the filter functions as well.

Alternativly this resolver could return a "default payment provider" (the first or a configured one) when its null. The checkout mutation itself should use the same default payment provider.

This would also solve a problem that i observed when i showcased unchained to someone in the playground:
You need to do multiple mutations until the cart can be checked out: login, add products, set payment provider, set delivery provider, set address. i think setting payment provider and delivery provider should not be mandatory and instead use the above mentioned default provider (the same value that cart.payment.provider returns).

**Comment by pozylon** [comment]
All cart actions trigger an invalidation so this feature is actually already built and has been tested, there needs to be another reason in that specific case that thinks the payment provider is still valid.

Orders.updateCalculation triggers initProviders on order which invalidates payment and delivery, Orders.updateCalculation is called as a central invalidation function that runs after all cart/order manipulating actions. 

Problem lies somewhere here maybe: OrderDiscounts.createManualOrderDiscount

**Comment by pozylon** [comment]
Just tested:

```
mutation {
  addCartProduct(productId: "33005367.001") {
    _id
    order {
      _id
      total {
        amount
      }
      payment {
        _id
      }
    }
  }
  addCartDiscount(code: "0000000000000") {
    _id
    order {
      _id
      total {
        amount
      }
      supportedPaymentProviders {
        _id
      }
    }
  }
}

```

Correctly results in:

```
"addCartProduct": {
      "_id": "tEpovcrserHpv36yX",
      "order": {
        "_id": "8RdfM7J46kSzxFPQP",
        "total": {
          "amount": 1280,
          "__typename": "Money"
        },
        "payment": {
          "_id": "paEbsWgFNJTGeZ3Nd",
          "__typename": "OrderPaymentInvoice"
        },
        "__typename": "Order"
      },
      "__typename": "OrderItem"
    },
    "addCartDiscount": {
      "_id": "zTxf8upm9Juj29c4S",
      "order": {
        "_id": "8RdfM7J46kSzxFPQP",
        "total": {
          "amount": 0,
          "__typename": "Money"
        },
        "supportedPaymentProviders": [
          {
            "_id": "free",
            "__typename": "PaymentProvider"
          }
        ],
        "__typename": "Order"
      },
      "__typename": "OrderDiscount"
    }
```

As you can see, after the first mutation, the provider was invoice (default), after adding a coupon with a balance of 50, the total is reduced to 0 and the provider is set to the first supported. This works by re-running payment.filterSupportedProviders

**Comment by macrozone** [comment]
doing recalculations does not really solve all cases. 

`filterSupportedProviders` might define ANY condition to filter out a provider. E.g. consider this outlandish condition:

- credit cart payment is only allowed during weekdays

Its easy to define this in `filterSupportedProviders`, but now you don't know when to rerun `updateCalculation`. 

The underlying problem is, that you try to have the database represent the perfect state, but thats not possible. in fact your business logic together with the db represent the state of the app,  not the db alone.

so if the db says, this order has payment provider xxx, but this provider is currently invalid, than this order has no payment provider asigned, no matter whats written in the db. Keeping the db consistent with the business logic at any time is nearly impossible given the goals of unchained to be able to customize everything (stuff like "weather dependent saussage prices").

**Comment by pozylon** [comment]
> If the cart resolver returns a provider that is invalid (not returned by the available providers resolver), than this is clearly a bug.

Agreed, but that does not happen

**Comment by macrozone** [comment]
i have another problem now that is related to this.

filterSupportedProviders should not be called by some recalculations, but instead exactly when its asked: fetching providers through graphql or do the checkout mutation (or maybe additionaly when I change a provider on the cart through a mutation).

currently, it looks like it is called, when i just change the quantity of an item in the cart. It should definitly not be tide to the recalculation of prices as explained above https://github.com/unchainedshop/unchained/issues/332#issuecomment-795099972
