### ISSUE TITLE
[FEATURE REQUEST] add types for startPlatform

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#334]
**Introduction**

`startPlatform` is the first "touchpoint" for a developer with unchained and also the central function to customize it.

Without typings its really hard to work with it and i think its deterring for new developers.

**Is your feature request related to a problem? Please describe.**

see above

**Describe the solution you'd like**

startPlatform should be fully typed and be precise on what to send where. I think it should also be grouped a bit more carefully as it will send its configuration to different parts (e.g. apollo server config should be in a "server" or "graphqlServer" property)

**Describe the design of the solution in detail**

no details yet

**Describe alternatives you've considered**

without typings, the documentation and examples have to be excellent. types do not replace documentations of course, but it makes it easier to understand whats possible without looking into the documentation.

**Additional context**

none

**Comment by pozylon** [comment]
done in newest rc
