### ISSUE TITLE
[FEATURE REQUEST] Send an Email when an Order gets canceled

### ISSUE THREAD

**Issue by nabbl** [unchainedshop/unchained#348]
**Introduction**
 Send an Email when an Order gets canceled

**Describe the solution you'd like**
I want to have a new Status for email sending. If the admin cancels an order the user who ordered should get an email

**Describe the design of the solution in detail**
Would be great if this is optional and could be set as a flag in boot.ts

**Comment by pozylon** [comment]
rejectOrder is implemented in newest rc.
