### ISSUE TITLE
unchained:core-products@0.61.3 breaks image tags

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#352]
**Describe the bug**

Product.addMediaLink can no longer set tags, because of this commit

https://github.com/unchainedshop/unchained/commit/8d848e8b3199c4baebfd07df4d718ec89f82543a#diff-9dad0a39b61c28f2b0e37d21e6659ef6c271d02b83ef08b75c700077cdc910f3

as you see, tags will always be set to `[]`, even if you pass tags.

**To Reproduce**

sorry no reproduction, but should be obvious

**Expected behavior**

Product.addMediaLink can set tags

**Comment by Mikearaya** [comment]
This is fixed now

**Comment by pozylon** [comment]
nice, I will do a release tomorrow

**Comment by Mikearaya** [comment]
@pozylon  include work queue filter with it if possible
