### ISSUE TITLE
[FEATURE REQUEST] Add thumbnail for media files

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#355]
**Introduction**
currently, only image media files can have a thumbnail but I think it would be good if we have a thumbnail field for other media types (document, pdf, video...) so that there is something to show on the front end no matter the media type.

**Describe the solution you'd like**
add new thumbnail field on media type returned by the server. 

**Describe the design of the solution in detail**
we can process the media file and extract the image either at initial upload or when the resource is requested (even at a resolver level), I suggest the former. the latter one has the advantage of backward compatibility though. 
so if it's an image just create a thumbnail size and resolution of the same image or use the image as a thumbnail. if media is a document extract the first page on the server side and store it as a thumbnail value for the image. The same with video though it's storing some type of screenshot of the video

**Describe alternatives you've considered**
It's not pretty but we can use static files as a thumbnail for document types and video or music. each document type will have a default thumbnail and based on the meme type use that as a thumbnail. this is with no doubt the easiest alternative.

**Comment by pozylon** [comment]
Currently, no thumbnail field exists at all, that on product media was added in userspace to the project by extending the graphql type.

Now that we have used different approaches to tackle that in our last projects with different up- and downsides (thumbor & next/image), I think it's propably enough to just document how to add a thumbnail field and pipe it to thumbor, we could add a  "cookbook" chapter to the docs with a new article "Server-side thumbnails with Thumbor" outlining how to extend a project

**Comment by Mikearaya** [comment]
I agree to extend the schema for most types should not be done but this is a file type and currently passing `meta` a file object doesn't work. so there must be some way to upload a shrunk version of an image.
either 
- do it automatically whenever an image file is uploaded create a thumbnail version of it in the backend, give flexibility for them by allowing them to pass the size of a thumbnail as env or even by a plugin, and put the URL of the thumbnail on the product meta `product.meta.thumbnail` then a simple extending the graphql schema to get the value
- extend the DB schema to hold a thumbnail field
-

**Comment by pozylon** [comment]
On Unchained always the original is beeing saved and thumbnails should be generated on-demand and then cached, this is what thumbor does for us so we only have to return the URL of the thumbnail, this is the extension snippet I was thinking of on the resolver:

Schema
```
enum ThumbnailSize {
  SMALL
  MEDIUM
}

extend type Media {
  thumbnail(size: ThumbnailSize!): String!
}
```

Media.js
```
const { THUMBOR_ENDPOINT, THUMBOR_SECRET } = process.env;
export default {
  thumbnail(media, { size = "SMALL" } = {}) {
    const file = media.file();
    const url = file.link('original');

    if (!THUMBOR_ENDPOINT || !THUMBOR_SECRET) return url;

    const parameters =
      size === "SMALL" ? '300x0' : '900x0';
    const unsafePath = `${parameters}/${url}`;
    const hash = crypto
      .createHmac('sha1', THUMBOR_SECRET)
      .update(unsafePath)
      .digest('base64');

    const safeHash = hash.replace(/\+/gi, '-').replace(/\//gi, '_');

    const safeUrl = `${THUMBOR_ENDPOINT}/${safeHash}/${unsafePath}`;
    return safeUrl;
  },
}
```

**Comment by pozylon** [comment]
@Mikearaya It's beneficial to on-demand + cache because the frontend can adjust the parameters for how big the thumbnails shall be. If you do it on upload and there is a change on how big the images shall be or how they are converted, you have to reprocess all already uploaded originals.

**Comment by Mikearaya** [comment]
@pozylon on-demand makes sense it will give the frontend the flexibility. 
to even pass more power to the frontend `ThumbnailSize` could be the dimension (WIDTH and HEIGHT) instead o enum of SMALL and MEDIUM. 
but I think we can take it future and instead of forcing users to use thumbor, it should be possible to somehow register a function that generates the URL using any image cropping service they prefer. default unchained. implementation of thumbor will be available

**Comment by pozylon** [comment]
Yeah that makes sense but maybe he wants face detection so that's some other completely different parameters. Extending the example will help a bit.

What do you mean by default unchained? By default support thumbor when endpoint is set?

**Comment by Mikearaya** [comment]
@pozylon yes by default the thumbor URL generator class registers the above thumbor URL generator function and works by setting the envs. here is an abstract version of it
```
MediaUrlGenerator.getThumnailUrl = function generateThumborUrl(media, options) {
  const file = media.file();
    const url = file.link('original');

    if (!THUMBOR_ENDPOINT || !THUMBOR_SECRET) return url;

    const parameters =
      size === "SMALL" ? '300x0' : '900x0';
    const unsafePath = `${parameters}/${url}`;
    const hash = crypto
      .createHmac('sha1', THUMBOR_SECRET)
      .update(unsafePath)
      .digest('base64');

    const safeHash = hash.replace(/\+/gi, '-').replace(/\//gi, '_');

    const safeUrl = `${THUMBOR_ENDPOINT}/${safeHash}/${unsafePath}`;
    return safeUrl;
}

```
users can override or register new functions to work this.

```
MediaUrlGenerator.getThumbnail = someFunction(url, option)
```

````

export default {
  thumbnail(media,option) {
    const file = media.file();
    const url = file.link('original');
return  MediaUrlGenerator.getThumbnail(url);
  },
}
````

**Comment by pozylon** [comment]
Don't you think this is overly complicated like this? I mean users could overwrite a default resolver like usually by doing even when there is already a default implementation:

Media.js
```
export default {
  thumbnail: customThumbnailField
}
```

**Comment by pozylon** [comment]
I'm not against providing a default thumbnail resolver for the media's based on that simple thumbor implementation but the extra   config fn in between seems not necessary.

**Comment by Mikearaya** [comment]
@pozylon sorry I've overlooked the possibility of overriding defined resolver. this is much simpler
