### ISSUE TITLE
[FEATURE REQUEST] B2C multivendor?

### ISSUE THREAD

**Issue by uyasarkocal** [unchainedshop/unchained#364]
I'm simply amazed by how modular and convenient this system is built. 

Any plans on making it into a multivendor system? Or if I decide to do it, would you recommend it architecture wise?

**Comment by pozylon** [comment]
@uyasarkocal Thanks, I'll write about it in github discussions.

**Comment by pozylon** [comment]
@uyasarkocal https://github.com/unchainedshop/unchained/discussions/381
