### ISSUE TITLE
[core] Add tests

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#37]
# Summary
- [ ] integration tests for the api package

## Integration Tests

Queries:
- [x] me: User
- [x] users(...): [User!]!
- [x] user(...): User
- [x] products(...): [Product!]!
- [x] product(...): Product
- [x] productCatalogPrices(...): [ProductPrice!]!
- [x] translatedProductTexts(...): [ProductTexts!]!
- [x] translatedProductMediaTexts(...): [ProductMediaTexts!]!
- [x] translatedProductVariationTexts(...): [ProductVariationTexts!]!
- [x] languages(...): [Language]!
- [x] language(...): Language
- [x] countries(...): [Country!]!
- [x] country(...): Country
- [x] currencies(...): [Currency!]!
- [x] currency(...): Currency
- [x] deliveryProviders(...): [DeliveryProvider!]!
- [x] deliveryProvider(...): DeliveryProvider
- [x] deliveryInterfaces(...): [DeliveryInterface!]!
- [x] warehousingProviders(...): [WarehousingProvider!]!
- [x] warehousingProvider(...): WarehousingProvider
- [x] warehousingInterfaces(...): [WarehousingInterface!]!
- [x] paymentProviders(...): [PaymentProvider!]!
- [x] paymentProvider(...): PaymentProvider
- [x] paymentInterfaces(...): [PaymentInterface!]!
- [x] orders(...): [Order!]!
- [x] order(...): Order
- [x] logs(...): [Log!]!
- [x] shopInfo: Shop!
- [x] assortments(...): [Assortment!]!
- [x] assortment(...): Assortment
- [x] translatedAssortmentTexts(...): [AssortmentTexts!]!
- [x] translatedFilterTexts(...): [FilterTexts!]!
- [x] filters(...): [Filter!]!
- [x] filter(...): Filter
- [x] productReviews(...): [ProductReview!]!
- [x] productReview(...): [ProductReview!]!
- [x] quotations(...): [Quotation!]!
- [x] quotation(...): Quotation
- [ ] search: SearchResult

Mutations:
- [x] loginWithPassword(...): LoginMethodResponse
- [x] createUser(...): LoginMethodResponse
- [x] changePassword(...): SuccessResponse
- [x] forgotPassword(...): SuccessResponse
- [x] resetPassword(...): LoginMethodResponse
- [x] logout(...): SuccessResponse
- [x] verifyEmail(...): LoginMethodResponse
- [x] resendVerificationEmail(...): SuccessResponse
- [x] loginAsGuest: LoginMethodResponse
- [x] createCart(...): Order!
- [ ] addCartProduct(...): OrderItem!
- [x] addMultipleCartProducts(...): [OrderItem]!
- [x] addCartDiscount(...): OrderDiscount!
- [x] addCartQuotation(...): OrderItem!
- [x] updateCart(...): Order!
- [x] emptyCart(...): Order
- [x] checkoutCart(...): Order!
- [x] updateCartItem(...): OrderItem!
- [x] removeCartItem(...): OrderItem!
- [x] removeCartDiscount(...): OrderDiscount!
- [x] setOrderDeliveryProvider(...): Order!
- [x] setOrderPaymentProvider(...): Order!
- [x] updateOrderDeliveryShipping(...): OrderDeliveryShipping!
- [x] updateOrderDeliveryPickUp(...): OrderDeliveryPickUp!
- [x] updateOrderPaymentCard(...): OrderPaymentCard!
- [x] updateOrderPaymentInvoice(...): OrderPaymentInvoice!
- [x] updateOrderPaymentGeneric(...): OrderPaymentGeneric!
- [x] removeOrder(...): Order!
- [x] confirmOrder(...): Order!
- [x] payOrder(...): Order!
- [x] deliverOrder(...): Order!
- [x] updateUserAvatar(...): User
- [x] updateEmail(...): User
- [x] updateUserTags(...): User
- [x] updateUserProfile(...): User
- [x] enrollUser(...): User
- [x] setPassword(...): User
- [x] setRoles(...): User
- [x] createProduct(...): Product!
- [x] publishProduct(...): Product!
- [x] unpublishProduct(...): Product!
- [x] removeProduct(...): Product!
- [x] updateProduct(...): Product
- [x] updateProductCommerce(...): Product
- [x] updateProductSupply(...): Product
- [x] updateProductWarehousing(...): Product
- [x] updateProductTexts(...): [ProductTexts!]!
- [ ] addProductMedia(...): ProductMedia!
- [x] removeProductMedia(...): ProductMedia!
- [x] reorderProductMedia(...): [ProductMedia!]!
- [x] updateProductMediaTexts(...): [ProductMediaTexts!]!
- [x] removeProductVariation(...): ProductVariation!
- [x] removeProductVariationOption(...): ProductVariation!
- [x] updateProductVariationTexts(...): [ProductVariationTexts!]!
- [x] createProductVariation(...): ProductVariation!
- [x] createProductBundleItem(...): Product!
- [x] removeBundleItem(...): Product!
- [x] createProductVariationOption(...): ProductVariation!
- [x] addProductAssignment(...): Product!
- [x] removeProductAssignment(...): Product!
- [x] createLanguage(...): Language!
- [x] updateLanguage(...): Language!
- [x] setBaseLanguage(...): Language!
- [x] removeLanguage(...): Language!
- [x] createCountry(...): Country!
- [x] updateCountry(...): Country!
- [x] setBaseCountry(...): Country!
- [x] removeCountry(...): Country!
- [x] createCurrency(...): Currency!
- [x] updateCurrency(...): Currency!
- [x] removeCurrency(...): Currency!
- [x] createPaymentProvider(...): PaymentProvider!
- [x] updatePaymentProvider(...): PaymentProvider!
- [x] removePaymentProvider(...): PaymentProvider!
- [x] createDeliveryProvider(...): DeliveryProvider!
- [x] updateDeliveryProvider(...): DeliveryProvider!
- [x] removeDeliveryProvider(...): DeliveryProvider!
- [x] createWarehousingProvider(...): WarehousingProvider!
- [x] updateWarehousingProvider(...): WarehousingProvider!
- [x] removeWarehousingProvider(...): WarehousingProvider!
- [x] createAssortment(...): Assortment!
- [x] updateAssortment(...): Assortment!
- [x] setBaseAssortment(...): Assortment!
- [x] removeAssortment(...): Assortment!
- [x] updateAssortmentTexts(...): [AssortmentTexts!]!
- [x] addAssortmentProduct(...): AssortmentProduct!
- [x] removeAssortmentProduct(...): AssortmentProduct!
- [x] reorderAssortmentProducts(...): [AssortmentProduct!]!
- [x] addAssortmentLink(...): AssortmentLink!
- [x] removeAssortmentLink(...): AssortmentLink!
- [x] reorderAssortmentLinks(...): [AssortmentLink!]!
- [x] addAssortmentFilter(...): AssortmentFilter!
- [x] removeAssortmentFilter(...): AssortmentFilter!
- [x] reorderAssortmentFilters(...): [AssortmentFilter!]!
- [x] createFilter(...): Filter!
- [x] updateFilter(...): Filter!
- [x] removeFilter(...): Filter!
- [x] removeFilterOption(...): Filter!
- [x] updateFilterTexts(...): [FilterTexts!]!
- [x] createFilterOption(...): Filter!
- [x] createProductReview(...): ProductReview!
- [x] updateProductReview(...): ProductReview!
- [x] removeProductReview(...): ProductReview!
- [x] addProductReviewVote(...): ProductReviewVote!
- [x] requestQuotation(...): Quotation!
- [x] verifyQuotation(...): Quotation!
- [x] rejectQuotation(...): Quotation!
- [x] makeQuotationProposal(...): Quotation!

**Comment by pozylon** [comment]
Conversation about typescript/tests #32

**Comment by macrozone** [comment]
we could probably start with integration tests for all queries and mutation. This should really be straight forward and would cover a lot of surface.

**Comment by pozylon** [comment]
I would prefer to use a complete test framework where I don't have to use different toolsets for integration and unit tests, choose between assertion libs etc. But maybe there is too many downsides? Do you have experience with https://jestjs.io/? @macrozone

**Comment by pozylon** [comment]
But I'm totally with you starting with the integration tests

**Comment by pozylon** [comment]
Added bookmarks tests

**Comment by pozylon** [comment]
I'm going to close this issue and add a new one about reviewing the test surface
