### ISSUE TITLE
controlpanel does not fetch all products to use in product assigment

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#40]
the dropdown here is limited to 10 products:

<img width="805" alt="Bildschirmfoto 2019-03-20 um 11 01 08" src="https://user-images.githubusercontent.com/1972353/54675777-83364a80-4aff-11e9-80df-ffdb3c146c02.png">

also it should probably only fetch "SIMPLE_PRODUCTS"

**Comment by pozylon** [comment]
Using query products without a limit will limit to 10 in that case, it's bad that the default values are not communicated through the schema, will change that as well
