### ISSUE TITLE
Mutation.updateUserProfile replaces existing unrelated data with new

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#405]
**Describe the bug**
if you call `updateUserProfile` 2 times with `profile.customFields` set to different values it will replace the value set on the first call with the value given on the second call.

**To Reproduce**
call
```
updateUserProfile(userId: 'x', profile: {
customFields: {
phoneNumbers: [{number: '0912887733', type: 'mobile'}]
}
})


updateUserProfile(userId: 'x', profile: {
customFields: {
addresses: [{city 'x', country: 'y'}]
}
})

```
in this case, `phoneNumbers` will be replaced

**Expected behavior**
it should not replace values set to different keys other than the ones provided on the actual call.

**Comment by pozylon** [comment]
@Mikearaya I agree but on the other hand this whole "customFields" thing does not go hand-in-hand with the new way of defining extra fields.

Maybe we should say defining an extension of the input field is the way to go, like:

```
extend input UserProfileInput {
  phoneNumbers: [DynopticPhoneNumberInput!]
}
```

And then in Users.updateProfile we change the logic to store any "non-standard" field under the meta or customFields field
