### ISSUE TITLE
add resolver minPrice to Products

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#41]
this returns the minimal price for a product

- for simple products its just the catalog price
- for bundle products its probably the sum of the bundlet items
- for configurable products its the price of the assigned products which is the lowest

this helps to do something like: "Pricing starting at ..."

**Comment by pozylon** [comment]
This opens up a question about bundle products: Is the price of a bundle the sum of the bundled items or does it have it's own pricing logic?

Bic Mac: 6.50
Cola: 3.50
Pommes: 3.50

Total of bundled items: CHF 13.50

Bic Mac Menu Small (Bundle): 11.50

**Comment by pozylon** [comment]
And thinking in that direction, what if the simple product is priced differently because of configuration:

<img width="943" alt="Bildschirmfoto 2019-03-21 um 17 08 58" src="https://user-images.githubusercontent.com/2109393/54766714-0d63d900-4bfc-11e9-82e3-899cf5e9556c.png">

**Comment by pozylon** [comment]
Nonetheless I could really use this feature for a client project I'm currently involved in.

**Comment by pozylon** [comment]
We could solve this issue if we returned multiple "catalogPrices" instead of one "catalogPrice"

**Comment by pozylon** [comment]
Client-side you could then find out that there are 2 prices with the same maxQuantity and show the range or only min or only max
