### ISSUE TITLE
[FEATURE REQUEST] products and assortments should accept full text search

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#410]
Currently `Query.products` and `Query.assortments` endpoints are only filterable by tags, slugs & status. but i think it should be possible to search a product using texts to search by title and subtitles at least. 

there is an alternative endpoint to search products and assortments (searchProducts and searchAssortments) however @pozylon  "only show linked products and are suspect to plugins filtering out products in some ways".

this is not great when you have thousands of products.

**Comment by pozylon** [comment]
Superseeded by #436
