### ISSUE TITLE
Missleading updateFilterTexts schema

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#416]
currently schema is defined as `mutation updateFilterTexts($filterId: ID!, $filterOptionValue: String, $texts: [UpdateFilterTextInput!]!)`
where `UdateFilterTypeInput` is  expected as array while it actually work when passed object 

**Change**
`mutation updateFilterTexts($filterId: ID!, $filterOptionValue: String, $texts: UpdateFilterTextInput!)`

**Comment by pozylon** [comment]
Weird… when did that change

**Comment by pozylon** [comment]
https://github.com/unchainedshop/unchained/blob/a4c7af33d2ad94703b0f850416d4b9659d308456/packages/core-filters/db/helpers.js#L294

All good, also the new version works fine with the array
