### ISSUE TITLE
allow to update cart item confiugration

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#43]
currently we have updateCartItemQuantity, but other property can't be updated.

introduce 

```
updateCartItem(
itemId: ID!
quantity: Int = 1
configuration: ...

): OrderItem!
```

**Comment by macrozone** [comment]
updating the cart item is easy, but it resolves a big design flaw:

configurable products that get added to the cart get resolved, so updating the configuration does nothing, you can't change a variation that way.

### Discussion:

we should think about reverting  the resolving of products that get added to the cart.  think changing the product silently when adding it will lead to a lot of problems and workarounds. A product with its configuration already perfectly describe what's in the cart/order. You can always resolve the assigned product if you really need to (e.g. for ean and price)

**Comment by macrozone** [comment]
I now implemented a fix, where i reuse product.resolveOrderableProduct. Will push a PR soon

**Comment by pozylon** [comment]
A configurable product is only a proxy and has no SKU. Therefore, delivery date estimations, pricing etc. is not possible for a configurable product.

Only products that have an SKU can get delivered and only those should remain on the order. Carts can stay open for days and changes in the assignment matrix of the configurable product could lead to different products, this is much worse than .

> configurable products that get added to the cart get resolved, so updating the configuration does nothing, you can't change a variation that way

In your pull request I think you actually solved that by re-resolving the product on changed configuration, which is the perfect way of solving that issue I think.

**Comment by pozylon** [comment]
Ah I just saw the second comment. Do you think there is any other problems we could slide into with the current design after applying your fix?

**Comment by pozylon** [comment]
It's important to mention that normally, ConfigurableProducts are only used for a "Facade/Proxy" like it's done here:

https://www.apple.com/ch-de/shop/buy-iphone/iphone-xr

When you add the configured iPhone to the cart it's already resolved to it's SKU as you can see it in the title of the product that was put into the cart:

https://www.apple.com/ch-de/shop/bag

**Comment by macrozone** [comment]
> Ah I just saw the second comment. Do you think there is any other problems we could slide into with the current design after applying your fix?

works flawlessly so far. 

The bigger problem is the whole handling of vectors and assigments.

i think every assignment should have a unique key and if you put that in the cart, it should store that assignmentId or variantId instead of a configuration. 

so the offer in the cart should look something like this in my opinion:

```
{
   product: <The configurable product>
   variantId: <Id that identifies the assigned product
   variantProduct: <The resolved product>
}
```

doing it with the configuration is very awkward.

E.g. take this drop down which allows the user to change the selected variant in the cart:


<img width="818" alt="Bildschirmfoto 2019-03-22 um 12 03 22" src="https://user-images.githubusercontent.com/1972353/54818891-9fbaba00-4c9a-11e9-8249-68bbd96e61da.png">

In the code, this look like this...


```
const CartItem = ({
  style,
  className,
  item,
  setProductVariation,
}: Props) => {
  const selectedAssigment =
    item.originalProduct.assignments &&
    item.configuration &&
    item.originalProduct.assignments.find(a =>
      Boolean(
        a.vectors.find(vector =>
          Boolean(
            item.configuration.find(
              config =>
                config.key === vector.variation.key &&
                config.value === vector.option.value
            )
          )
        )
      )
    )


  return (
    <CartItemBase style={style} className={className}>


      {get(item, 'originalProduct.assignments.length') > 1 ? (
        <select
          value={selectedAssigment && selectedAssigment._id}
          onChange={e => {
            const assigment = item.originalProduct.assignments.find(
              a => a._id === e.target.value
            )
            if (assigment)
              setProductVariation({
                cartItemId: item._id,
                configuration: assigment.vectors.map(v => ({
                  key: v.variation.key,
                  value: v.option.value,
                })),
              })
          }}
        >
          {item.originalProduct.assignments.map(assigment => (
            <option key={assigment._id} value={assigment._id}>
              {assigment.product.texts.title}
            </option>
          ))}
        </select>
      ) : (
        item.product.texts.title
      )}
    </CartItemBase>
  )
}

```


but this would be much much much more intuitiv:

```

const CartItem = ({
  style,
  className,
  item,
  setProductVariation,
}: Props) => {


  return (
    <CartItemBase style={style} className={className}>
     
      {get(item, 'originalProduct.variants.length') > 1 ? (
        <select
          value={item.variantId}
          onChange={e => {
          
            setProductVariation({
            cartItemId: item._id,
            variantId: e.target.value
            })
        }}
       
        >
          {item.originalProduct.variants.map(variant => (
            <option key={variant._id} value={variant._id}>
              {variant.product.texts.title}
            </option>
          ))}
        </select>
      ) : (
        item.product.texts.title
      )}
    </CartItemBase>
  )
}
````

so what i suggest is:

- a product can have a flat list of variants.
- Every variant has an assigned product
- A product can optionally have options (color, size, etc.)
- every variant has a vector, which shows how you can get to that variant based on selected options


this solves both usecases:

- selecting a variant based on options
- selecting a variant directly based on a flat list of all variants

I think the current implementation solves also this usecases, but it overcomplicates things a bit, also the terminology is not very intuitiv.

**Comment by pozylon** [comment]
Changing the variant by id only works when there is only one variation, right? Maybe we should solve that by introducing a less complicated type of product. Nevertheless let's merge that PR and we can tackle that in another issue.

**Comment by macrozone** [comment]
> Changing the variant by id only works when there is only one variation, right? 

no. Every OrderPosition always has one concrete product in a selected variant. From a OrderPosition you get the product and all its variant and can select between the variants either directly by their id or by a vector. Same goes for adding a product to a cart. From the product you can get all its variant and you have to pass the productId and a variantId, instead of productId and a configuration.

> Maybe we should solve that by introducing a less complicated type of product.

no, you can do the exact same thing, just the current version is too complicated and can be simplified.

**Comment by pozylon** [comment]
> no. Every OrderPosition always has one concrete product in a selected variant. From a OrderPosition you get the product and all its variant and can select between the variants either directly by their id or by a vector. Same goes for adding a product to a cart. From the product you can get all its variant and you have to pass the productId and a variantId, instead of productId and a configuration.

If you have a case where this is fine, you don't actually need the vector stuff and you could achieve the same UI by having all products in a single assortment then use the SimpleProduct.siblings property to list all other products in the same assortment.

**Comment by pozylon** [comment]
Hm, using siblings is maybe not right because of other problems that could arise when having more than one assortmentLink, but instead of altering the configuration to make the ConfigurableProduct resolve to another variant, I would just remove the orderItem and re-add the product.

**Comment by pozylon** [comment]
Closing this as the configuration can now be changed through updateCartItem
