### ISSUE TITLE
[FEATURE REQUEST]All list queries should accept text search

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#436]
- [x] Filters
- [x] Products
- [x] Assortments
- [x] Orders
- [x] Quotations
- [x] Subscription
- [x] Currencies
- [x] Languages
- [x] Events
- [x] Work Queue

**Comment by pozylon** [comment]
I think it should mainly focus on the important fields that are not filtered by the other query params in those queries already: 

- Query.filters for should search _id, key and option keys with lowercase regex.
- Query.products should search the _id, the slugs and the sku (only admin)
- Query.assortments should search the _id and the slugs (only admin)
- Query.orders should search the _id, the orderNumber, the contact phoneNumber and email
- Query.quotations and Query.enrollments similar to orders
- Query.currencies, Query.languages, Query.countries: _id and isoCode
- Query.events should search the _id (and the payload maybe?)
- Query.workQueue should search _id, originalWorkId, worker, input (and the result and error maybe?)

**Comment by pozylon** [comment]
@Mikearaya happy to receive a PR with products/assortments beeing extended to take a search query based on the specification above.

**Comment by Mikearaya** [comment]
@pozylon it won't be that long :)
