### ISSUE TITLE
Query.assortments is not filtering root assortments only

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#455]
*The bug**
By default `query.assortments` accepts a `includeLeaves` parameter which is supposed to return when leaf node when it's truth. currently, it seems like this filter is not working and is returning all assortments (leaf and root) all the time instead

**Comment by pozylon** [comment]
![Bildschirmfoto 2022-05-17 um 09 46 07](https://user-images.githubusercontent.com/2109393/168757670-7d374d58-463f-4f60-8e5a-87f64f58fe29.png)
works just fine? @Mikearaya  (current master)

**Comment by Mikearaya** [comment]
@pozylon try it on publicare unchained1.0 branch maybe we should fix it only on publicare engine migration because if a user passed `assortmentSelector` `{}` then this problem occurs

**Comment by pozylon** [comment]
just tested it with the following queries, no bug:
- Query.assortments
- Query.assortmentsCount
- Query.searchAssortments

will try in publicare 1.0 branch and try to spot the issue

**Comment by Mikearaya** [comment]
@pozylon the default query doesnt have issue its when you try to use findAssortments helper the problem.
