### ISSUE TITLE
Bulk import error

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#457]
**Describe the bug**
Bulk import works and imports the data successfully but it always fails with the below error.

![Screenshot from 2022-05-13 09-38-01](https://user-images.githubusercontent.com/9751246/168226674-202364ca-f1ec-450b-a9a6-b76e8ee83c88.png)

it's caused after a successful import when trying to map productIds of assortments. specifically `buildProductIds`

**Comment by pozylon** [comment]
Gonna look into this
