### ISSUE TITLE
Assortment links out of memory error

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#468]
when you try to add assortment Link, assortment Product Link or remove Assortment Product Link you get the below error.

![Screenshot from 2022-05-31 09-51-48](https://user-images.githubusercontent.com/9751246/171111711-05ed0fb7-6918-4b53-98b2-1eacb7a294b4.png)

![Screenshot from 2022-05-31 09-51-58](https://user-images.githubusercontent.com/9751246/171111725-6db295d5-3a9b-474c-985b-78af86dec9f1.png)

**Comment by Mikearaya** [comment]
happens on remove too

**Comment by pozylon** [comment]
I have reproduced this by doing an infinite loop with assortment children:

- Add Assortment Test1
- Add Assortment Test2
- Go to Test1, add Test2 as Subassortment
- Go to Test2, add Test1 as Subassortment

So to fix this bug we should throw an error when somebody is trying to do this. Unchained only supports Directed Acyclic Graphs not Cyclic Graphs.

**Comment by pozylon** [comment]
Basically, you will need to add a check and a custom error when somebody tries to add an assortment link that would end up in a cycle
