### ISSUE TITLE
Duplicate Cart item 

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#478]
**Describe the bug**
After adding products as a user that is not logged in and logging into an account that exists cart items added as a guest user are not merged, instead, are shown as a separate product.

**To Reproduce**
1. log in using an existing user account
2. Add product to the cart
3. log out
4. login in as a guest user `loginAsGuest`
5. add the same product to the cart
6. log in to the user account in step one

The current result is the 2 identical products will be in the cart as a separate cart item 

**Expected behavior**
Items added into a cart as a guest user should be merged to an existing user account when a user log in.

**Comment by pozylon** [comment]
Fixed
