### ISSUE TITLE
query packages with multiple tags should do an AND, not an OR

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#51]
```
query PackageProdcuts($tags: [String!], $limit: Int = 100000) {
  products(tags: ["foo", "bar"]) {

  }
}

```

this should query products having both tags, not products that have either tag.

reasoning: you can mimick the current behaviour with multiple queries, wheras it is impossible to query the products containing both tags at once

**Comment by pozylon** [comment]
right
