### ISSUE TITLE
in orders rename originalProduct to product and product to variantProduct

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#52]
`originalProduct` is not a good name, better use `baseProduct` or so. Or even better:

let `product` either be the SimpleProduct or the ConfigurableProduct.

if its a `ConfigurableProduct` it has a `variantProduct: Product` property

**Comment by macrozone** [comment]
this is one simplification i would do based on the discussion in https://github.com/unchainedshop/unchained/issues/43

**Comment by pozylon** [comment]
I'm not happy with originalProduct either but not sure if baseProduct is better suited as it's not really a base product in the sense that the children are dependent. There could be many different baseProducts for the same product in a cart.

That just shifts the complexity from the mutation to the query, it would mean rendering orderItems and their sku's with conditionals when displaying the current cart for example:

```
if product.__typename equals ConfigurableProduct
   display variantProduct.sku
else
   display product.sku
```

**Comment by macrozone** [comment]
sku could always resolve to the variantProduct if its a configured product. We are taking about graphql, baby!

and: you seldom have to access the sku anyway in the frontend...

**Comment by macrozone** [comment]
this pr shows also that its a bit awkward at the moment, e.g. show the product and variant title in the email: https://github.com/unchainedshop/unchained/pull/53

**Comment by pozylon** [comment]
That is not correct, in a B2B shop like Publicare the SKU is extremely important. I see your points and your use case but sometimes making something easy for you means making stuff harder for other cases.... And in issue #53 you need the title of the ConfigurableProduct which is also not the way how it is normally used in shops ;)

**Comment by pozylon** [comment]
To clarify:

Normally you would want to display the most specific information and pictures in a cart, confirmation email or so: Assuming you have a ConfigurableProduct "box" with a picture that shows all different boxes and two concrete ones "red box" and "blue box" with a picture of a red box and a picture of a blue box, the most important data is the texts and pictures of the resolved product and not the one of the configurableProduct

**Comment by pozylon** [comment]
The name "ConfigurableProduct" is very bad though, it should be "ProductLookupProxy" or something that clearly states what the intention of usage is.

**Comment by pozylon** [comment]
Closing this, will link the discussion to "refactor variants"
