### ISSUE TITLE
logout mutation throws error

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#546]
**Describe the bug**

calling `logout` without a token (or empty string) throws error if no cookie is present: "The \"data\" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined"

**To Reproduce**

call `logout` without a token or token as empty string.

**Expected behavior**

logout can always be called without an error

**Comment by pozylon** [comment]
Cookie presence is propably not the reason, a user could be logged in with an api token.

But anyways, logout mutations should only throw when the explicit token provided does not exist, for any other error cases it should just return success: false.

So like you said, when calling logout without a token it should return success: false when there was no session assigned to the call. 

Empty string is different and should throw in my opinion.
