### ISSUE TITLE
send more errors to the client

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#6]
e.g. when doing 

```
mutation {
  checkout {
    _id
    confirmed
  }
}
```

you get an error, if you did not update the deliveryProvider and paymentProvider of the cart. The error is logged on the server ("No payment provider selected") but the client has no further information.

we should send the error "No payment provider selected" to the client, no matter if in debug or prod

**Comment by pozylon** [comment]
fixed in PR #18
