### ISSUE TITLE
Refactor Discounting system

### ISSUE THREAD

**Issue by pozylon** [unchainedshop/unchained#61]
- Replace Flag with Methods (isTriggerSystem)
- Solve the context puzzle in discounts as a future direction for all modules
- Replace static isDeletionAllowed, ... with non-static
- Rethink / review naming and code abstraction levels for: DiscountDirector.discountConfigurationForCalculation, discountForPricingAdapterKey, resolveDiscountKeyFromStaticCode....

**Comment by macrozone** [comment]
i would also rename the discount configurations, as far as i understand there is `fixedRate` and `rate`.

I suggest `fixedAmount`  (or `fixedValue`) and `percent` or so.

**Comment by pozylon** [comment]
Closing in favor of #115
