### ISSUE TITLE
 tokens filter

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/unchained#621]
Currently there is no filter parameters supported on Query.tokens it would be great if it supports atleast a basic qierystring filter on some of it fields, even better if it is extended to support users filter. 
However this creates a direct dependency of users module to.make it work, but its something to think about

**Comment by Mikearaya** [comment]
i've added a basic text search here https://github.com/unchainedshop/unchained/pull/620

**Comment by pozylon** [comment]
merged
