### ISSUE TITLE
Where should i host unchained?

### ISSUE THREAD

**Issue by tiepz** [unchainedshop/unchained#63]
hello,

I would like to try unchained for family shop, but still have no idea where to host, please guide me.

Can i deploy unchained on netlify.com?
Or meteojs.com hosting or digitalocean?

**Comment by tiepz** [comment]
should i try on meteor.com?

**Comment by pozylon** [comment]
You can host an unchained-based project through Meteor Galaxy,  as a Docker container (see examples/minimal) or standalone, please see https://guide.meteor.com/deployment.html for further information
