### ISSUE TITLE
error when deploy to meteor galaxy

### ISSUE THREAD

**Issue by thoInteractive** [unchainedshop/unchained#69]
hi, i got these error when make an deploy to my galaxy,

C:\Users\Administrator\Desktop\unchained\examples\minimal>meteor deploy my-meteor-app.meteorapp.com --settings settings.json
unchained:core-settings: updating npm dependencies -- lodash.get...
unchained:core-files: updating npm dependencies -- lodash.merge...
=> Errors while initializing project:

While building package unchained:core-settings:
error: couldn't install npm packages from npm-shrinkwrap: Command failed: C:\Windows\system32\cmd.exe /c
C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
install

While building package unchained:core-files:
error: couldn't install npm packages from npm-shrinkwrap: Command failed: C:\Windows\system32\cmd.exe /c
C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
install

C:\Users\Administrator\Desktop\unchained\examples\minimal>meteor build --architecture os.linux.x86_64 --directory .build
unchained:core-settings: updating npm dependencies -- lodash.get...
unchained:core-files: updating npm dependencies -- lodash.merge...
=> Errors while initializing project:

While building package unchained:core-settings:
error: couldn't install npm packages from npm-shrinkwrap: Command failed: C:\Windows\system32\cmd.exe /c
C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
install

While building package unchained:core-files:
error: couldn't install npm packages from npm-shrinkwrap: Command failed: C:\Windows\system32\cmd.exe /c
C:\Users\Administrator\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
install

Please help?

**Comment by pozylon** [comment]
Hi there, this is not the right place for questions, please use our spectrum.chat channel
