### ISSUE TITLE
Using GraphQL Nexus for the schemas

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained#71]
Would increase the developer experience. Low prio, just wanted to start the conversation what you guys (@macrozone, @pozylon) think about this.

https://nexus.js.org/

Would be worth a try to just auto-convert all the schemas and see if it still works.

**Comment by pozylon** [comment]
I tried to follow the documentation and the reasoning why I should use nexus compared to graphql schema files but I just don't get it :S

**Comment by schmidsi** [comment]
It's mainly:

"giving you IDE completion and type error catching out of the box!"

**Comment by schmidsi** [comment]
https://nexus.js.org/docs/why-graphql-nexus

**Comment by pozylon** [comment]
I see some advantages of the approach especially when using type inference & static checking but at the moment I'm not sure if this approach gains much popularity in the long run. What about we re-evaluate this together with TypeScript at the end of this year?

**Comment by schmidsi** [comment]
Agreed

**Comment by macrozone** [comment]
@pozylon we are going to evaulate prisma for the admin/cms on our upcoming project and will probably use nexus there as well (nexus is made by the prisma team). so we will have insights on that!
