### ISSUE TITLE
refactor payments

### ISSUE THREAD

**Issue by macrozone** [unchainedshop/unchained#9]
what about the following packages:

- unchained:payment-invoice
- unchained:payment-stripe
- unchained:payment-paypal
- ...

instead of one unchained:core-payment?

the idea is, that you could just add the packages you need, without needing to import the plugins. This would fit more how meteor packages work.

the single payment-* packages would then require unchained:payment-core where base classes, etc. are defined.

**Comment by macrozone** [comment]
edit: same goes for core-pricing plugins. these should probably be standalone packages

**Comment by pozylon** [comment]
Hm, I see your point and it would definitely match better with atmosphere packages. On the other hand I think we already have a lot of packages and I guess we could introduce issues when different plugins depend on different versions of unchained:payment (somewhere the adapter logic needs to lie) where as the platform defines the version that is used. How to manage that?

Let's have a look at core-pricing like you suggested. It would end up in an additional 9 packages just for core-pricing at the current state.

**Comment by macrozone** [comment]
@pozylon the amount of packages is not per-se a problem. usually you would have an umbrella-package that requires all the absolutly nesseary core-packages.

so an actually app would have such a package list:

unchained:core
unchained:pricing-swiss
unchained:payment-datatrans

and so on.

i understand the dependency problem with different versions of core-pricing, but that is a future problem. Having packages with clear dependency should actually mitigate that problem or at least should make it obvious, when you have a conflict.

Having the plugins as package would also help developers creating new packages, because you immediatly see how to build one.

with the current approach on the other hand the dev needs to either:

- fork the whole core-payments packages and add the payments there (bad, unless pushed upstream)
- or implement the custom payment plugin in user-space and require all the needed classes directly from core-payments (bad, because you still have dependency problems when core-payments gets updated breaking your custom plugin.)

generally, small packages with a clear surface is usually the better approach. it reduces noise and makes reasoning about solutions much easier. 

I think this package approach makes most sense in areas, where you expect the developer to extend unchained anyway. Like custom payments, custom pricing, custom delivery. Having clear packages for that as a template enables the devs to build their own plugin-packages and maybe even contribute back to unchained.

**Comment by pozylon** [comment]
I didn't look at the plugins as something that gets contributed back to the unchained engine until now and I feel it's that "having more meteor" and the restricted way of dependency management that makes me skeptical.

Having plugins as packages is definetely the way to got, if only we could solve that in a more agnostic way so we don't have to force contributers to publish atmosphere packages. What if we had an npm package "@unchainedshop/plugin" that hosts those various adapter classes?

Like:
meteor/unchained:core-pricing depends on @unchainedshop/plugin at version 1.1
meteor/unchained:core-payment depends on @unchainedshop/plugin at version 1.1
@userx/payment-weibo depends on @unchainedshop/plugin at version 1.*

Or maybe we could even have packages like @unchainedshop/payment-plugin?

**Comment by macrozone** [comment]
> I didn't look at the plugins as something that gets contributed back to the unchained engine 


but you should, because you are contributor yourself ;-) 

goal should primary be, that a plugin  has a small surface and can easily be added and used as template for new plugins on the same part.


> until now and I feel it's that "having more meteor" and the restricted way of dependency management that makes me skeptical.


true, but its atm the easiest solution. The meteor package approach enables you to add new plugins just with "meteor add xx", without modifiying your entry point.

doing a plugin system without such a mechanism is not that easy. You basically would need to refactor everything. you would need to instantiate everything in one entry point, otherwise you can't influence the creation of instances. 

E.g. you can't just have a plugin that exports directly an instance of a db collection unless you export always a function that creates this instance. Then you have a chance to pass runtime context (like configuration and injections) into the creation of your collection/plugin/whatever. 

> Having plugins as packages is definetely the way to got, if only we could solve that in a more agnostic way so we don't have to force contributers to publish atmosphere packages. What if we had an npm package "@unchainedshop/plugin" that hosts those various adapter classes?

not sure if you can easily workaround the above mentioned problem without big refactoring. (maybe i am wrong)

**Comment by pozylon** [comment]
Closing in favor of #115
