### ISSUE TITLE
Create user is not persiting the profile

### ISSUE THREAD

**Issue by claudiocro** [unchainedshop/unchained#98]
Take this mutation:

```
mutation CreateUser($profile: ShopUserProfileInput) {
  createUser(email: "cro+3@panter.ch", plainPassword: "asdf", profile: $profile) {
    id
    token
    tokenExpires
  }
}
```
with this variables:

```
"profile":{
    "phoneMobile":"786981729",
    "address": {
      "lastName":"Romano",
      "firstName":"Claudio",
      "company":"compa",
      "addressLine":"Steinhaldestrasse 52",
      "postalCode":"8002",
      "city":"Zürich",
      "countryCode":"Schweiz"
    }
  }
}
```

If you query:

```
{
  me {
    _id
    profile {
      gender
      birthday
      address {
        firstName
        lastName
        company
        addressLine
        postalCode
        countryCode
        regionCode
        city
      }
    }
  }
}
```

The profile is empty

**Comment by pozylon** [comment]
@schmidsi and me had a short discussion about this topic and we think in the end having a salutation in addresses is a veloplus specific requirement. We assume that other shops will not need this field at all. Looking at it that way, we have decided to not add the field to the core but show a solution on how to extend the address for specific projects.

**Comment by pozylon** [comment]
Thanks, fixed in https://github.com/unchainedshop/unchained/commit/dc25fe34f32508145fd59cfe166cf88c13dae166
