### ISSUE TITLE
Salutation in address

### ISSUE THREAD

**Issue by claudiocro** [unchainedshop/unchained#99]
Take the situation where we have a different billing oder shipping address it would be helpful to add a `salution` field to the address to address the Customer correctly at the given address.

**Comment by pozylon** [comment]
@schmidsi and me had a short discussion about this topic and we think in the end having a salutation in addresses is a veloplus specific requirement. We assume that other shops will not need this field at all. Looking at it that way, we have decided to not add the field to the core but show a solution on how to extend the address for specific projects.
